/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD - do not edit directly. */
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RecentViewPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// gdrive.ts
var import_obsidian = require("obsidian");
var TOKEN_URL = "https://oauth2.googleapis.com/token";
var AUTH_URL = "https://accounts.google.com/o/oauth2/v2/auth";
var SCOPE = "https://www.googleapis.com/auth/drive";
var FOLDER_MIME = "application/vnd.google-apps.folder";
var EXPORT_MAP = {
  "application/vnd.google-apps.document": { mime: "text/markdown", ext: "md" },
  "application/vnd.google-apps.spreadsheet": { mime: "text/csv", ext: "csv" },
  "application/vnd.google-apps.presentation": {
    mime: "application/pdf",
    ext: "pdf"
  },
  "application/vnd.google-apps.drawing": { mime: "image/png", ext: "png" }
};
function getNode(mod) {
  var _a;
  try {
    const req = window.require;
    return (_a = req ? req(mod) : null) != null ? _a : null;
  } catch (e) {
    return null;
  }
}
function sanitizeName(name) {
  return name.replace(/[\\/:*?"<>|]/g, "_").trim() || "untitled";
}
function encodeForm(data) {
  return Object.entries(data).map(([k, v]) => `${encodeURIComponent(k)}=${encodeURIComponent(v)}`).join("&");
}
function isDesktop() {
  return getNode("http") !== null;
}
function parseDriveFolderId(input) {
  const s = input.trim();
  const folders = s.match(/\/folders\/([a-zA-Z0-9_-]+)/);
  if (folders)
    return folders[1];
  const idParam = s.match(/[?&]id=([a-zA-Z0-9_-]+)/);
  if (idParam)
    return idParam[1];
  const open = s.match(/\/d\/([a-zA-Z0-9_-]+)/);
  if (open)
    return open[1];
  if (/^[a-zA-Z0-9_-]{10,}$/.test(s))
    return s;
  return null;
}
var GoogleDriveClient = class {
  constructor(app, getStore, persist) {
    this.app = app;
    this.getStore = getStore;
    this.persist = persist;
    this.accessToken = "";
    this.expiry = 0;
  }
  /** Always read the live settings object (never a stale captured copy). */
  get store() {
    return this.getStore();
  }
  isConfigured() {
    return !!(this.store.gdriveClientId && this.store.gdriveClientSecret);
  }
  isConnected() {
    return !!this.store.gdriveRefreshToken;
  }
  async disconnect() {
    this.store.gdriveRefreshToken = "";
    this.accessToken = "";
    this.expiry = 0;
    await this.persist();
  }
  /** Run the loopback OAuth flow and store a refresh token (desktop only). */
  async connect() {
    if (!this.isConfigured()) {
      throw new Error("Set your Google OAuth Client ID and Secret first.");
    }
    const http = getNode("http");
    if (!http)
      throw new Error("Google Drive sign-in is desktop-only.");
    const { code, redirectUri } = await new Promise((resolve, reject) => {
      let redirectUri2 = "";
      const server = http.createServer((req, res2) => {
        var _a;
        try {
          const u = new URL((_a = req.url) != null ? _a : "", "http://127.0.0.1");
          const code2 = u.searchParams.get("code");
          const err = u.searchParams.get("error");
          res2.writeHead(200, { "Content-Type": "text/html" });
          res2.end(
            "<html><body style='font-family:sans-serif'>Recent View: authorization received. Return to Obsidian to finish connecting, then close this tab.</body></html>"
          );
          server.close();
          if (err)
            reject(new Error(err));
          else if (code2)
            resolve({ code: code2, redirectUri: redirectUri2 });
          else
            reject(new Error("No authorization code returned."));
        } catch (e) {
          reject(e);
        }
      });
      server.on("error", reject);
      server.listen(0, "127.0.0.1", () => {
        var _a;
        const addr = server.address();
        const port = typeof addr === "object" && addr ? addr.port : 0;
        redirectUri2 = `http://127.0.0.1:${port}`;
        const authUrl = `${AUTH_URL}?` + encodeForm({
          client_id: this.store.gdriveClientId,
          redirect_uri: redirectUri2,
          response_type: "code",
          scope: SCOPE,
          access_type: "offline",
          prompt: "consent"
        });
        const electron = getNode("electron");
        if ((_a = electron == null ? void 0 : electron.shell) == null ? void 0 : _a.openExternal)
          electron.shell.openExternal(authUrl);
        else
          window.open(authUrl, "_blank");
      });
      window.setTimeout(() => {
        try {
          server.close();
        } catch (e) {
        }
        reject(new Error("OAuth timed out."));
      }, 3e5);
    });
    const res = await (0, import_obsidian.requestUrl)({
      url: TOKEN_URL,
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: encodeForm({
        code,
        client_id: this.store.gdriveClientId,
        client_secret: this.store.gdriveClientSecret,
        redirect_uri: redirectUri,
        grant_type: "authorization_code"
      }),
      throw: false
    });
    if (res.status >= 400) {
      throw new Error(`Token exchange failed: ${res.text}`);
    }
    const json = res.json;
    if (!json.refresh_token) {
      throw new Error(
        "No refresh token returned. Remove the app's access at myaccount.google.com/permissions and try again."
      );
    }
    this.store.gdriveRefreshToken = json.refresh_token;
    this.accessToken = json.access_token;
    this.expiry = Date.now() + json.expires_in * 1e3;
    await this.persist();
  }
  async getAccessToken() {
    if (this.accessToken && Date.now() < this.expiry - 6e4) {
      return this.accessToken;
    }
    if (!this.store.gdriveRefreshToken) {
      throw new Error("Not connected to Google Drive.");
    }
    const res = await (0, import_obsidian.requestUrl)({
      url: TOKEN_URL,
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: encodeForm({
        client_id: this.store.gdriveClientId,
        client_secret: this.store.gdriveClientSecret,
        refresh_token: this.store.gdriveRefreshToken,
        grant_type: "refresh_token"
      }),
      throw: false
    });
    if (res.status >= 400) {
      throw new Error(`Token refresh failed: ${res.text}`);
    }
    const json = res.json;
    this.accessToken = json.access_token;
    this.expiry = Date.now() + json.expires_in * 1e3;
    return this.accessToken;
  }
  async api(url, init = {}) {
    var _a, _b;
    const token = await this.getAccessToken();
    const res = await (0, import_obsidian.requestUrl)({
      url,
      method: (_a = init.method) != null ? _a : "GET",
      headers: { Authorization: `Bearer ${token}`, ...(_b = init.headers) != null ? _b : {} },
      body: init.body,
      throw: false
    });
    if (res.status >= 400) {
      throw new Error(`Drive API ${res.status}: ${res.text}`);
    }
    return res;
  }
  async getFolderName(folderId) {
    var _a;
    const res = await this.api(
      `https://www.googleapis.com/drive/v3/files/${folderId}?fields=name&supportsAllDrives=true`
    );
    return (_a = res.json.name) != null ? _a : "Google Drive";
  }
  async listChildren(folderId) {
    var _a, _b;
    const out = [];
    let pageToken = "";
    do {
      const q = encodeURIComponent(`'${folderId}' in parents and trashed=false`);
      const url = `https://www.googleapis.com/drive/v3/files?q=${q}&fields=nextPageToken,files(id,name,mimeType)&pageSize=1000&supportsAllDrives=true&includeItemsFromAllDrives=true` + (pageToken ? `&pageToken=${pageToken}` : "");
      const res = await this.api(url);
      const json = res.json;
      out.push(...(_a = json.files) != null ? _a : []);
      pageToken = (_b = json.nextPageToken) != null ? _b : "";
    } while (pageToken);
    return out;
  }
  async ensureDir(path) {
    const adapter = this.app.vault.adapter;
    const parts = path.split("/").filter(Boolean);
    let cur = "";
    for (const part of parts) {
      cur = cur ? `${cur}/${part}` : part;
      if (!await adapter.exists(cur))
        await adapter.mkdir(cur);
    }
  }
  /** Recursively download a Drive folder into a vault directory. */
  async downloadFolder(folderId, vaultDir) {
    await this.ensureDir(vaultDir);
    let count = 0;
    for (const child of await this.listChildren(folderId)) {
      if (child.mimeType === FOLDER_MIME) {
        count += await this.downloadFolder(
          child.id,
          `${vaultDir}/${sanitizeName(child.name)}`
        );
        continue;
      }
      const dl = await this.downloadFile(child);
      if (!dl)
        continue;
      await this.app.vault.adapter.writeBinary(`${vaultDir}/${dl.name}`, dl.data);
      count++;
    }
    return count;
  }
  async downloadFile(child) {
    let url;
    let name = sanitizeName(child.name);
    if (child.mimeType.startsWith("application/vnd.google-apps")) {
      const exp = EXPORT_MAP[child.mimeType];
      if (!exp)
        return null;
      url = `https://www.googleapis.com/drive/v3/files/${child.id}/export?mimeType=${encodeURIComponent(exp.mime)}`;
      if (!name.toLowerCase().endsWith(`.${exp.ext}`))
        name += `.${exp.ext}`;
    } else {
      url = `https://www.googleapis.com/drive/v3/files/${child.id}?alt=media&supportsAllDrives=true`;
    }
    const res = await this.api(url);
    return { name, data: res.arrayBuffer };
  }
  async createFolder(name, parentId) {
    const res = await this.api(
      "https://www.googleapis.com/drive/v3/files?supportsAllDrives=true&fields=id",
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ name, mimeType: FOLDER_MIME, parents: [parentId] })
      }
    );
    return res.json.id;
  }
  async createFile(name, parentId, data) {
    const meta = await this.api(
      "https://www.googleapis.com/drive/v3/files?supportsAllDrives=true&fields=id",
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ name, parents: [parentId] })
      }
    );
    const id = meta.json.id;
    await this.updateFileContent(id, data);
  }
  async updateFileContent(id, data) {
    await this.api(
      `https://www.googleapis.com/upload/drive/v3/files/${id}?uploadType=media&supportsAllDrives=true`,
      { method: "PATCH", body: data }
    );
  }
  /** Ensure a nested folder path exists under a Drive folder; return leaf id. */
  async ensureSubfolder(parentId, names) {
    let current = parentId;
    for (const name of names) {
      const children = await this.listChildren(current);
      const match = children.find(
        (c) => c.name === name && c.mimeType === FOLDER_MIME
      );
      current = match ? match.id : await this.createFolder(name, current);
    }
    return current;
  }
  /** Upload (create or update) one file into rootFolderId/<relDirParts>. */
  async uploadSingleFile(rootFolderId, file, relDirParts) {
    const parentId = await this.ensureSubfolder(rootFolderId, relDirParts);
    const data = await this.app.vault.readBinary(file);
    const children = await this.listChildren(parentId);
    const match = children.find(
      (c) => c.name === file.name && c.mimeType !== FOLDER_MIME
    );
    if (match)
      await this.updateFileContent(match.id, data);
    else
      await this.createFile(file.name, parentId, data);
  }
  /** Recursively upload a vault folder's contents into a Drive folder. */
  async uploadFolder(vaultDir, folderId) {
    const folder = this.app.vault.getAbstractFileByPath(vaultDir);
    if (!(folder instanceof import_obsidian.TFolder))
      return 0;
    const existing = await this.listChildren(folderId);
    const byName = new Map(existing.map((c) => [c.name, c]));
    let count = 0;
    for (const child of folder.children) {
      if (child instanceof import_obsidian.TFolder) {
        const match = byName.get(child.name);
        const subId = match && match.mimeType === FOLDER_MIME ? match.id : await this.createFolder(child.name, folderId);
        count += await this.uploadFolder(child.path, subId);
      } else if (child instanceof import_obsidian.TFile) {
        const data = await this.app.vault.readBinary(child);
        const match = byName.get(child.name);
        if (match && match.mimeType !== FOLDER_MIME) {
          await this.updateFileContent(match.id, data);
        } else {
          await this.createFile(child.name, folderId, data);
        }
        count++;
      }
    }
    return count;
  }
};

// main.ts
var VIEW_TYPE_PROJECT_LIST = "recent-view-project-list";
var VIEW_TYPE_PROJECT_CONTENT = "recent-view-project-content";
var DEFAULT_DATA_NOTE = "ProjectView.md";
var LEGACY_DATA_NOTE = "RecentView.md";
var DEFAULT_SETTINGS = {
  dataNotePath: DEFAULT_DATA_NOTE,
  gdriveClientId: "",
  gdriveClientSecret: "",
  gdriveRefreshToken: ""
};
var DATA_NOTE_HEADER = "# ProjectView data\n\nThis note is managed by the **ProjectView** plugin and stores this vault's projects. Avoid editing the JSON block below by hand.";
function genId() {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 8);
}
function sanitizeVaultName(name) {
  return name.replace(/[\\/:*?"<>|]/g, "_").trim() || "Google Drive";
}
function enableReorder(container, onReorder) {
  const items = () => Array.from(container.children).filter(
    (el) => el.dataset.rvId != null
  );
  let dragging = null;
  for (const item of items()) {
    item.draggable = true;
    item.addClass("rv-pin-draggable");
    item.addEventListener("dragstart", (e) => {
      var _a;
      dragging = item;
      item.addClass("rv-dragging");
      if (e.dataTransfer) {
        e.dataTransfer.effectAllowed = "move";
        e.dataTransfer.setData("text/plain", (_a = item.dataset.rvId) != null ? _a : "");
      }
    });
    item.addEventListener("dragend", () => {
      item.removeClass("rv-dragging");
      dragging = null;
      onReorder(items().map((i) => {
        var _a;
        return (_a = i.dataset.rvId) != null ? _a : "";
      }));
    });
  }
  container.addEventListener("dragover", (e) => {
    e.preventDefault();
    if (!dragging)
      return;
    if (e.dataTransfer)
      e.dataTransfer.dropEffect = "move";
    const y = e.clientY;
    const siblings = items().filter((i) => i !== dragging);
    let before = null;
    for (const sib of siblings) {
      const box = sib.getBoundingClientRect();
      if (y < box.top + box.height / 2) {
        before = sib;
        break;
      }
    }
    if (before)
      container.insertBefore(dragging, before);
    else
      container.appendChild(dragging);
  });
}
function applyOrder(list, idOf, orderedIds) {
  const byId = new Map(list.map((item) => [idOf(item), item]));
  const result = [];
  for (const id of orderedIds) {
    const item = byId.get(id);
    if (item) {
      result.push(item);
      byId.delete(id);
    }
  }
  for (const item of byId.values())
    result.push(item);
  return result;
}
function buildDataNote(data) {
  return `${DATA_NOTE_HEADER}

\`\`\`json
${JSON.stringify(
    data,
    null,
    2
  )}
\`\`\`
`;
}
function parseDataNote(content) {
  var _a, _b;
  const match = content.match(/```json\s*([\s\S]*?)```/);
  if (!match)
    return null;
  try {
    const parsed = JSON.parse(match[1]);
    return {
      projects: (_a = parsed.projects) != null ? _a : [],
      activeProjectId: (_b = parsed.activeProjectId) != null ? _b : null
    };
  } catch (e) {
    return null;
  }
}
function showMenu(menu, event, paneEl, btn) {
  btn == null ? void 0 : btn.addClass("is-active");
  const prevPointerEvents = paneEl.style.pointerEvents;
  paneEl.style.pointerEvents = "none";
  menu.onHide(() => {
    btn == null ? void 0 : btn.removeClass("is-active");
    paneEl.style.pointerEvents = prevPointerEvents;
  });
  menu.showAtMouseEvent(event);
}
var RecentViewPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.data = { projects: [], activeProjectId: null };
    this.settings = { ...DEFAULT_SETTINGS };
    this.isActivating = false;
    this.noteWriteTimer = null;
    // Live tab group (pane) per project, kept alive so switching just shows/hides
    // panes instead of closing and reopening notes.
    this.projectGroups = /* @__PURE__ */ new Map();
    // Stack of previously-active project ids, for the back button.
    this.navHistory = [];
    this._drive = null;
  }
  get drive() {
    if (!this._drive) {
      this._drive = new GoogleDriveClient(
        this.app,
        () => this.settings,
        () => this.saveSettings()
      );
    }
    return this._drive;
  }
  async onload() {
    await this.loadAll();
    this.addSettingTab(new RecentViewSettingTab(this.app, this));
    this.registerView(
      VIEW_TYPE_PROJECT_LIST,
      (leaf) => new ProjectListView(leaf, this)
    );
    this.registerView(
      VIEW_TYPE_PROJECT_CONTENT,
      (leaf) => new ProjectContentView(leaf, this)
    );
    this.addRibbonIcon(
      "folder-kanban",
      "Recent View: projects",
      () => this.activateListView()
    );
    this.addCommand({
      id: "open-projects-pane",
      name: "Open projects pane",
      callback: () => this.activateListView()
    });
    this.addCommand({
      id: "new-project",
      name: "Create new project",
      callback: () => new ProjectEditModal(this.app, this, null).open()
    });
    this.addCommand({
      id: "save-current-tabs",
      name: "Save current tabs to active project",
      callback: () => {
        const n = this.saveActiveProjectTabs(true);
        const p = this.getActiveProject();
        new import_obsidian2.Notice(
          p ? `RecentView: saved ${n} tab(s) to "${p.name}"` : "RecentView: no active project"
        );
      }
    });
    this.registerEvent(
      this.app.workspace.on("layout-change", () => this.onLayoutChange())
    );
    this.app.workspace.onLayoutReady(() => {
      this.arrangeLeftSidebar();
      const active = this.getActiveProject();
      if (active)
        void this.openProject(active);
      const onVaultChange = () => this.refreshContentView();
      this.registerEvent(this.app.vault.on("create", onVaultChange));
      this.registerEvent(this.app.vault.on("delete", onVaultChange));
      this.registerEvent(
        this.app.vault.on("rename", (file, oldPath) => {
          this.handlePathRename(oldPath, file.path);
          this.refreshContentView();
        })
      );
    });
  }
  onunload() {
    if (this.noteWriteTimer !== null) {
      window.clearTimeout(this.noteWriteTimer);
      this.noteWriteTimer = null;
      void this.writeDataNote();
    }
  }
  /**
   * Load settings (from the plugin's data.json) and project data (from the
   * note inside the vault). Falls back to migrating legacy project data that
   * older versions stored in data.json.
   */
  async loadAll() {
    var _a, _b, _c, _d, _e, _f, _g;
    const stored = (_a = await this.loadData()) != null ? _a : {};
    this.settings = {
      dataNotePath: stored.dataNotePath || DEFAULT_SETTINGS.dataNotePath,
      gdriveClientId: (_b = stored.gdriveClientId) != null ? _b : "",
      gdriveClientSecret: (_c = stored.gdriveClientSecret) != null ? _c : "",
      gdriveRefreshToken: (_d = stored.gdriveRefreshToken) != null ? _d : ""
    };
    let fromNote = await this.readDataNote();
    let needsWrite = false;
    if (!fromNote && this.settings.dataNotePath !== LEGACY_DATA_NOTE && await this.app.vault.adapter.exists(LEGACY_DATA_NOTE)) {
      try {
        fromNote = parseDataNote(
          await this.app.vault.adapter.read(LEGACY_DATA_NOTE)
        );
      } catch (e) {
        fromNote = null;
      }
      if (fromNote)
        needsWrite = true;
    }
    if (fromNote) {
      this.data = fromNote;
      if (needsWrite)
        await this.writeDataNote();
    } else if (stored.projects) {
      this.data = {
        projects: stored.projects,
        activeProjectId: (_e = stored.activeProjectId) != null ? _e : null
      };
      await this.writeDataNote();
    } else {
      this.data = { projects: [], activeProjectId: null };
    }
    const migrateNotes = (list) => (list != null ? list : []).map(
      (n) => typeof n === "string" ? { path: n } : n
    );
    for (const project of this.data.projects) {
      project.lastOpenNotes = migrateNotes(project.lastOpenNotes);
      project.lastClosedNotes = migrateNotes(project.lastClosedNotes);
      project.pinned = (_f = project.pinned) != null ? _f : [];
      project.panes = ((_g = project.panes) != null ? _g : []).map((p) => ({
        id: p.id,
        name: p.name,
        lastOpenNotes: migrateNotes(p.lastOpenNotes),
        lastClosedNotes: migrateNotes(p.lastClosedNotes)
      }));
      if (project.activePaneId === void 0)
        project.activePaneId = null;
    }
  }
  async readDataNote() {
    const path = this.settings.dataNotePath;
    const adapter = this.app.vault.adapter;
    if (!path || !await adapter.exists(path))
      return null;
    try {
      return parseDataNote(await adapter.read(path));
    } catch (e) {
      return null;
    }
  }
  async writeDataNote() {
    const path = this.settings.dataNotePath;
    if (!path)
      return;
    const adapter = this.app.vault.adapter;
    const slash = path.lastIndexOf("/");
    if (slash > 0) {
      const dir = path.slice(0, slash);
      if (!await adapter.exists(dir))
        await adapter.mkdir(dir);
    }
    await adapter.write(path, buildDataNote(this.data));
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Persist settings immediately and schedule a debounced write of the project
   * data note (avoids hammering the vault/sync on every layout change).
   */
  async persist() {
    await this.saveSettings();
    if (this.noteWriteTimer !== null)
      window.clearTimeout(this.noteWriteTimer);
    this.noteWriteTimer = window.setTimeout(() => {
      this.noteWriteTimer = null;
      void this.writeDataNote();
    }, 600);
  }
  /** Persist immediately, used for infrequent but important edits. */
  async persistNow() {
    if (this.noteWriteTimer !== null) {
      window.clearTimeout(this.noteWriteTimer);
      this.noteWriteTimer = null;
    }
    await this.saveSettings();
    await this.writeDataNote();
  }
  getActiveProject() {
    var _a;
    return (_a = this.data.projects.find((p) => p.id === this.data.activeProjectId)) != null ? _a : null;
  }
  async togglePin(project, path) {
    if (!project.pinned)
      project.pinned = [];
    const i = project.pinned.indexOf(path);
    if (i >= 0)
      project.pinned.splice(i, 1);
    else
      project.pinned.push(path);
    await this.persistNow();
    this.refreshContentView();
  }
  /** Remove a folder from the project (does not delete it from the vault). */
  async removeFolderFromProject(project, folderPath) {
    project.folders = project.folders.filter((f) => f !== folderPath);
    await this.persistNow();
    this.refreshContentView();
  }
  /** Create an untitled note inside a folder and open it ready for naming. */
  async createNoteInFolder(folder, name = "") {
    const base = (name.trim() || "Untitled").replace(/[\\/:*?"<>|]/g, "_");
    const dir = folder.path === "/" ? "" : folder.path;
    let path = dir ? `${dir}/${base}.md` : `${base}.md`;
    let i = 1;
    while (this.app.vault.getAbstractFileByPath(path)) {
      path = dir ? `${dir}/${base} ${i}.md` : `${base} ${i}.md`;
      i++;
    }
    try {
      const file = await this.app.vault.create(path, "");
      this.focusActiveGroup();
      const leaf = this.app.workspace.getLeaf("tab");
      await leaf.openFile(file);
      window.setTimeout(() => {
        var _a;
        const titleEl = leaf.view.containerEl.querySelector(
          ".inline-title"
        );
        if (titleEl) {
          titleEl.focus();
          (_a = document.getSelection()) == null ? void 0 : _a.selectAllChildren(titleEl);
        }
      }, 50);
    } catch (e) {
      new import_obsidian2.Notice(`Couldn't create note: ${e.message}`);
    }
  }
  async addFolderToProject(project, folder) {
    if (!project.folders.includes(folder.path)) {
      project.folders.push(folder.path);
      await this.persistNow();
      this.refreshContentView();
      return;
    }
    new import_obsidian2.Notice("Folder is already in this project.");
  }
  async addNoteToProject(project, file) {
    if (!project.notes.includes(file.path)) {
      project.notes.push(file.path);
      await this.persistNow();
      this.refreshContentView();
      return;
    }
    new import_obsidian2.Notice("Note is already in this project.");
  }
  /** Update stored paths across all projects when a file/folder is renamed. */
  handlePathRename(oldPath, newPath) {
    var _a, _b, _c, _d;
    const remap = (p) => {
      if (p === oldPath)
        return newPath;
      if (p.startsWith(oldPath + "/"))
        return newPath + p.slice(oldPath.length);
      return p;
    };
    let changed = false;
    const track = (before, after) => {
      if (before !== after)
        changed = true;
      return after;
    };
    const remapNotes = (list) => list.map((n) => ({ ...n, path: track(n.path, remap(n.path)) }));
    for (const project of this.data.projects) {
      project.folders = project.folders.map((f) => track(f, remap(f)));
      project.notes = project.notes.map((n) => track(n, remap(n)));
      project.pinned = ((_a = project.pinned) != null ? _a : []).map((p) => track(p, remap(p)));
      project.lastOpenNotes = remapNotes(project.lastOpenNotes);
      project.lastClosedNotes = remapNotes((_b = project.lastClosedNotes) != null ? _b : []);
      for (const pane of (_c = project.panes) != null ? _c : []) {
        pane.lastOpenNotes = remapNotes(pane.lastOpenNotes);
        pane.lastClosedNotes = remapNotes((_d = pane.lastClosedNotes) != null ? _d : []);
      }
    }
    if (changed)
      void this.persist();
  }
  /** Set the order of pinned notes. */
  async setPinnedOrder(project, orderedPaths) {
    var _a;
    project.pinned = applyOrder((_a = project.pinned) != null ? _a : [], (p) => p, orderedPaths);
    await this.persistNow();
    this.refreshContentView();
  }
  /** Set the order of projects in the left pane. */
  async setProjectOrder(orderedIds) {
    this.data.projects = applyOrder(this.data.projects, (p) => p.id, orderedIds);
    await this.persistNow();
    this.refreshListView();
  }
  /** Set the order of a project's named panes. */
  async setPaneOrder(project, orderedIds) {
    project.panes = applyOrder(project.panes, (p) => p.id, orderedIds);
    await this.persistNow();
    this.refreshContentView();
  }
  async activateListView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_PROJECT_LIST)[0];
    if (!leaf) {
      const fileExplorer = workspace.getLeavesOfType("file-explorer")[0];
      if (fileExplorer) {
        leaf = workspace.createLeafBySplit(fileExplorer, "horizontal", true);
      } else {
        const left = workspace.getLeftLeaf(false);
        if (!left)
          return;
        leaf = left;
      }
      await leaf.setViewState({ type: VIEW_TYPE_PROJECT_LIST, active: true });
    }
    workspace.revealLeaf(leaf);
  }
  /**
   * Dock the Projects list above the native File Explorer in the left sidebar
   * (so the explorer is at the bottom). Re-creates the list leaf in the right
   * spot; the list view is rebuilt from data so nothing is lost.
   */
  arrangeLeftSidebar() {
    const { workspace } = this.app;
    const fileExplorer = workspace.getLeavesOfType("file-explorer")[0];
    if (!fileExplorer) {
      void this.activateListView();
      return;
    }
    for (const l of workspace.getLeavesOfType(VIEW_TYPE_PROJECT_LIST)) {
      l.detach();
    }
    const leaf = workspace.createLeafBySplit(fileExplorer, "horizontal", true);
    void leaf.setViewState({ type: VIEW_TYPE_PROJECT_LIST, active: true }).then(() => workspace.revealLeaf(leaf));
  }
  async activateContentView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_PROJECT_CONTENT)[0];
    if (!leaf) {
      const right = workspace.getRightLeaf(false);
      if (!right)
        return;
      leaf = right;
      await leaf.setViewState({
        type: VIEW_TYPE_PROJECT_CONTENT,
        active: true
      });
    }
    workspace.revealLeaf(leaf);
    this.refreshContentView();
  }
  refreshListView() {
    for (const leaf of this.app.workspace.getLeavesOfType(
      VIEW_TYPE_PROJECT_LIST
    )) {
      if (leaf.view instanceof ProjectListView)
        leaf.view.render();
    }
  }
  refreshContentView() {
    for (const leaf of this.app.workspace.getLeavesOfType(
      VIEW_TYPE_PROJECT_CONTENT
    )) {
      if (leaf.view instanceof ProjectContentView)
        leaf.view.render();
    }
  }
  /**
   * Open a project: show its live pane (tab group), creating it from the saved
   * notes the first time. Other projects' panes are hidden, not closed, so
   * their tabs keep their full editor state.
   */
  async openProject(project) {
    var _a;
    const current = this.data.activeProjectId;
    if (current && current !== project.id) {
      this.navHistory.push(current);
      if (this.navHistory.length > 50)
        this.navHistory.shift();
    }
    await this.showPane(project, (_a = project.activePaneId) != null ? _a : null);
  }
  canGoBack() {
    return this.navHistory.length > 0;
  }
  /** Return to the most recently selected project. */
  async goBack() {
    var _a;
    while (this.navHistory.length > 0) {
      const id = this.navHistory.pop();
      const project = this.data.projects.find((p) => p.id === id);
      if (project && project.id !== this.data.activeProjectId) {
        await this.showPane(project, (_a = project.activePaneId) != null ? _a : null);
        return;
      }
    }
    new import_obsidian2.Notice("No previous project.");
  }
  /** Unique key for a project's pane (main pane uses just the project id). */
  paneKey(projectId, paneId) {
    return paneId ? `${projectId}::${paneId}` : projectId;
  }
  /** The open-tabs list for a given pane (main pane stored on the project). */
  paneNotes(project, paneId) {
    var _a, _b;
    if (!paneId)
      return project.lastOpenNotes;
    return (_b = (_a = project.panes.find((p) => p.id === paneId)) == null ? void 0 : _a.lastOpenNotes) != null ? _b : [];
  }
  /** Recently closed notes for a pane, newest first. */
  paneClosedNotes(project, paneId) {
    var _a, _b, _c;
    if (!paneId)
      return (_a = project.lastClosedNotes) != null ? _a : [];
    return (_c = (_b = project.panes.find((p) => p.id === paneId)) == null ? void 0 : _b.lastClosedNotes) != null ? _c : [];
  }
  lastClosedNote(project, paneId) {
    var _a;
    return (_a = this.paneClosedNotes(project, paneId)[0]) != null ? _a : null;
  }
  setPaneNotes(project, paneId, notes) {
    if (!paneId) {
      project.lastOpenNotes = notes;
      return;
    }
    const pane = project.panes.find((p) => p.id === paneId);
    if (pane)
      pane.lastOpenNotes = notes;
  }
  setPaneClosedNotes(project, paneId, notes) {
    if (!paneId) {
      project.lastClosedNotes = notes;
      return;
    }
    const pane = project.panes.find((p) => p.id === paneId);
    if (pane)
      pane.lastClosedNotes = notes;
  }
  recordClosedNotes(project, paneId, closed) {
    if (closed.length === 0)
      return;
    const existing = this.paneClosedNotes(project, paneId);
    const next = [];
    for (const note of [...closed].reverse()) {
      if (!next.some((n) => n.path === note.path)) {
        next.push({ ...note, active: true });
      }
    }
    for (const note of existing) {
      if (!next.some((n) => n.path === note.path))
        next.push(note);
    }
    this.setPaneClosedNotes(project, paneId, next.slice(0, 20));
  }
  /**
   * Show a specific pane of a project: hide every other pane, restore (or
   * create) this one's tab group.
   */
  async showPane(project, paneId) {
    this.saveActiveProjectTabs();
    this.isActivating = true;
    this.data.activeProjectId = project.id;
    project.activePaneId = paneId;
    this.refreshListView();
    void this.activateContentView();
    const key = this.paneKey(project.id, paneId);
    try {
      let group = this.getLiveGroup(key);
      if (!group)
        group = await this.createPaneGroup(project, paneId);
      if (group) {
        this.projectGroups.set(key, group);
        this.applyGroupVisibility(key);
        this.focusGroup(group);
      }
    } catch (e) {
      console.error("[RecentView] failed to open pane", e);
    }
    await this.persist();
    window.setTimeout(() => {
      this.isActivating = false;
    }, 150);
  }
  /** Build a new tab group for a pane from its saved notes. */
  async createPaneGroup(project, paneId) {
    var _a;
    const notes = this.resolveNotes(this.paneNotes(project, paneId));
    const { workspace } = this.app;
    let firstLeaf;
    if (!this.hasAnyLiveGroup()) {
      const existing = [];
      workspace.iterateRootLeaves((leaf) => {
        existing.push(leaf);
      });
      firstLeaf = (_a = existing[0]) != null ? _a : workspace.getLeaf(false);
      for (const leaf of existing)
        if (leaf !== firstLeaf)
          leaf.detach();
    } else {
      const mru = workspace.getMostRecentLeaf(workspace.rootSplit);
      if (mru)
        workspace.setActiveLeaf(mru, { focus: false });
      firstLeaf = workspace.getLeaf("split");
    }
    if (notes.length === 0) {
      await firstLeaf.setViewState({ type: "empty" });
      return firstLeaf.parent;
    }
    const opened = [firstLeaf];
    await firstLeaf.openFile(notes[0].file, { eState: notes[0].eState });
    for (let i = 1; i < notes.length; i++) {
      const leaf = workspace.getLeaf("tab");
      await leaf.openFile(notes[i].file, { eState: notes[i].eState });
      opened.push(leaf);
    }
    const activeIndex = notes.findIndex((n) => n.active);
    workspace.setActiveLeaf(opened[activeIndex >= 0 ? activeIndex : 0], {
      focus: true
    });
    return firstLeaf.parent;
  }
  resolveNotes(list) {
    return list.map((n) => ({
      file: this.app.vault.getAbstractFileByPath(n.path),
      eState: n.eState,
      active: n.active === true
    })).filter(
      (n) => n.file instanceof import_obsidian2.TFile
    );
  }
  /** Create a new empty pane for a project and switch to it. */
  async addPane(project, name) {
    const pane = {
      id: genId(),
      name: name.trim() || `Pane ${project.panes.length + 1}`,
      lastOpenNotes: [],
      lastClosedNotes: []
    };
    project.panes.push(pane);
    await this.persistNow();
    await this.showPane(project, pane.id);
  }
  async renamePaneItem(project, paneId, name) {
    const pane = project.panes.find((p) => p.id === paneId);
    if (!pane)
      return;
    pane.name = name.trim() || pane.name;
    await this.persistNow();
    this.refreshContentView();
  }
  async deletePaneItem(project, paneId) {
    const key = this.paneKey(project.id, paneId);
    const group = this.projectGroups.get(key);
    if (group) {
      const toClose = [];
      this.app.workspace.iterateRootLeaves((leaf) => {
        if (this.leafInGroup(leaf, group))
          toClose.push(leaf);
      });
      for (const leaf of toClose)
        leaf.detach();
      this.projectGroups.delete(key);
    }
    project.panes = project.panes.filter((p) => p.id !== paneId);
    await this.persistNow();
    if (project.activePaneId === paneId) {
      await this.showPane(project, null);
    } else {
      this.refreshContentView();
    }
  }
  /** Switch to a pane and open all markdown notes in a folder as tabs in it. */
  async openFolderInPane(project, paneId, folder) {
    const files = [];
    import_obsidian2.Vault.recurseChildren(folder, (f) => {
      if (f instanceof import_obsidian2.TFile && f.extension === "md")
        files.push(f);
    });
    files.sort((a, b) => a.basename.localeCompare(b.basename));
    await this.showPane(project, paneId);
    await this.openFilesInActivePane(files);
  }
  /** Switch to a pane and open a single note in it. */
  async openNoteInPane(project, paneId, file) {
    await this.showPane(project, paneId);
    await this.openFilesInActivePane([file]);
  }
  /** Switch to a pane and reopen its most recently closed note. */
  async openLastClosedInPane(project, paneId) {
    const closed = [...this.paneClosedNotes(project, paneId)];
    while (closed.length > 0) {
      const note = closed.shift();
      if (!note)
        break;
      const file = this.app.vault.getAbstractFileByPath(note.path);
      if (!(file instanceof import_obsidian2.TFile))
        continue;
      this.setPaneClosedNotes(project, paneId, closed);
      await this.showPane(project, paneId);
      await this.openNoteStateInActivePane(note, file);
      this.saveActiveProjectTabs(true);
      await this.persistNow();
      return;
    }
    this.setPaneClosedNotes(project, paneId, []);
    await this.persistNow();
    new import_obsidian2.Notice("No recently closed tab for this pane.");
  }
  async openNoteStateInActivePane(note, file) {
    const group = this.getActiveGroup();
    if (!group)
      return;
    this.focusActiveGroup();
    let existing = null;
    this.app.workspace.iterateRootLeaves((leaf) => {
      var _a;
      if (!existing && this.leafInGroup(leaf, group) && ((_a = leaf.getViewState().state) == null ? void 0 : _a.file) === file.path) {
        existing = leaf;
      }
    });
    if (existing) {
      this.app.workspace.setActiveLeaf(existing, { focus: true });
      return;
    }
    await this.app.workspace.getLeaf("tab").openFile(file, { eState: note.eState });
  }
  async openFilesInActivePane(files) {
    const group = this.getActiveGroup();
    if (!group)
      return;
    this.focusActiveGroup();
    for (const file of files) {
      let existing = null;
      this.app.workspace.iterateRootLeaves((leaf) => {
        var _a;
        if (!existing && this.leafInGroup(leaf, group) && ((_a = leaf.getViewState().state) == null ? void 0 : _a.file) === file.path) {
          existing = leaf;
        }
      });
      if (existing)
        continue;
      await this.app.workspace.getLeaf("tab").openFile(file);
    }
  }
  /** A project's folders and all of their subfolders. */
  projectFolders(project) {
    const found = /* @__PURE__ */ new Map();
    for (const fp of project.folders) {
      const folder = this.app.vault.getAbstractFileByPath(fp);
      if (folder instanceof import_obsidian2.TFolder) {
        found.set(folder.path, folder);
        import_obsidian2.Vault.recurseChildren(folder, (f) => {
          if (f instanceof import_obsidian2.TFolder)
            found.set(f.path, f);
        });
      }
    }
    return [...found.values()].sort((a, b) => a.path.localeCompare(b.path));
  }
  /** All markdown files belonging to a project (folder contents + loose notes). */
  projectFiles(project) {
    const found = /* @__PURE__ */ new Map();
    for (const fp of project.folders) {
      const folder = this.app.vault.getAbstractFileByPath(fp);
      if (folder instanceof import_obsidian2.TFolder) {
        import_obsidian2.Vault.recurseChildren(folder, (f) => {
          if (f instanceof import_obsidian2.TFile && f.extension === "md")
            found.set(f.path, f);
        });
      }
    }
    for (const np of project.notes) {
      const f = this.app.vault.getAbstractFileByPath(np);
      if (f instanceof import_obsidian2.TFile)
        found.set(f.path, f);
    }
    return [...found.values()].sort(
      (a, b) => a.basename.localeCompare(b.basename)
    );
  }
  /** The container element of a tab group, or null if it's gone. */
  groupContainer(group) {
    const el = group.containerEl;
    return el != null ? el : null;
  }
  /** Return the pane's tab group if it still exists in the layout. */
  getLiveGroup(key) {
    if (!key)
      return null;
    const group = this.projectGroups.get(key);
    if (!group)
      return null;
    const el = this.groupContainer(group);
    if (!el || !el.isConnected) {
      this.projectGroups.delete(key);
      return null;
    }
    return group;
  }
  getActiveGroup() {
    var _a;
    const project = this.getActiveProject();
    if (!project)
      return null;
    return this.getLiveGroup(
      this.paneKey(project.id, (_a = project.activePaneId) != null ? _a : null)
    );
  }
  hasAnyLiveGroup() {
    for (const [key] of this.projectGroups) {
      if (this.getLiveGroup(key))
        return true;
    }
    return false;
  }
  leafInGroup(leaf, group) {
    var _a;
    let node = leaf;
    while (node) {
      if (node === group)
        return true;
      node = (_a = node.parent) != null ? _a : null;
    }
    return false;
  }
  /** Show the active project's pane, hide all others. */
  applyGroupVisibility(activeId) {
    for (const [projectId, group] of [...this.projectGroups]) {
      const el = this.groupContainer(group);
      if (!el || !el.isConnected) {
        this.projectGroups.delete(projectId);
        continue;
      }
      if (projectId === activeId) {
        el.style.display = "";
        el.style.flexGrow = "1";
        el.style.flexShrink = "1";
        el.style.flexBasis = "0";
        el.style.minWidth = "0";
        el.style.width = "";
      } else {
        el.style.display = "none";
      }
    }
  }
  /** Focus the most recently active leaf inside a group so its tab is shown
   *  (preserves which tab was active within that pane). */
  focusGroup(group) {
    const leaf = this.app.workspace.getMostRecentLeaf(group);
    if (leaf)
      this.app.workspace.setActiveLeaf(leaf, { focus: true });
  }
  /**
   * React to layout changes: snapshot the active pane's tabs, or — if the active
   * pane was removed because its last tab was closed — recreate it as an empty
   * new tab so the project always has a visible pane.
   */
  onLayoutChange() {
    var _a;
    if (this.isActivating)
      return;
    const project = this.getActiveProject();
    if (!project)
      return;
    const paneId = (_a = project.activePaneId) != null ? _a : null;
    const key = this.paneKey(project.id, paneId);
    if (this.getLiveGroup(key)) {
      this.saveActiveProjectTabs();
    } else {
      this.recordClosedNotes(project, paneId, this.paneNotes(project, paneId));
      this.setPaneNotes(project, paneId, []);
      void this.showPane(project, paneId);
    }
  }
  /** Focus the active project's pane (used before opening a note into it). */
  focusActiveGroup() {
    const group = this.getActiveGroup();
    if (group)
      this.focusGroup(group);
  }
  saveActiveProjectTabs(force = false) {
    var _a, _b;
    if (this.isActivating && !force)
      return -1;
    const project = this.getActiveProject();
    if (!project)
      return -1;
    const paneId = (_a = project.activePaneId) != null ? _a : null;
    const group = this.getLiveGroup(this.paneKey(project.id, paneId));
    if (!group)
      return -1;
    const activeLeaf = this.app.workspace.getMostRecentLeaf(
      this.app.workspace.rootSplit
    );
    const activePath = (_b = activeLeaf == null ? void 0 : activeLeaf.getViewState().state) == null ? void 0 : _b.file;
    const open = [];
    this.app.workspace.iterateRootLeaves((leaf) => {
      var _a2;
      if (!this.leafInGroup(leaf, group))
        return;
      const filePath = (_a2 = leaf.getViewState().state) == null ? void 0 : _a2.file;
      if (typeof filePath === "string" && !open.some((o) => o.path === filePath)) {
        open.push({
          path: filePath,
          eState: leaf.getEphemeralState(),
          active: filePath === activePath
        });
      }
    });
    const removed = this.paneNotes(project, paneId).filter(
      (note) => !open.some((o) => o.path === note.path)
    );
    this.recordClosedNotes(project, paneId, removed);
    this.setPaneNotes(project, paneId, open);
    void this.persist();
    return open.length;
  }
  /** Snapshot the open tabs belonging to a pane's tab group. */
  captureGroupTabs(group) {
    var _a;
    const activeLeaf = this.app.workspace.getMostRecentLeaf(
      this.app.workspace.rootSplit
    );
    const activePath = (_a = activeLeaf == null ? void 0 : activeLeaf.getViewState().state) == null ? void 0 : _a.file;
    const open = [];
    this.app.workspace.iterateRootLeaves((leaf) => {
      var _a2;
      if (!this.leafInGroup(leaf, group))
        return;
      const filePath = (_a2 = leaf.getViewState().state) == null ? void 0 : _a2.file;
      if (typeof filePath === "string" && !open.some((o) => o.path === filePath)) {
        open.push({
          path: filePath,
          eState: leaf.getEphemeralState(),
          active: filePath === activePath
        });
      }
    });
    return open;
  }
  /** A pane's saved default tab set (main pane uses project.defaultTabs). */
  paneDefaultTabs(project, paneId) {
    var _a, _b, _c;
    if (!paneId)
      return (_a = project.defaultTabs) != null ? _a : [];
    return (_c = (_b = project.panes.find((p) => p.id === paneId)) == null ? void 0 : _b.defaultTabs) != null ? _c : [];
  }
  paneHasDefaultTabs(project, paneId) {
    return this.paneDefaultTabs(project, paneId).length > 0;
  }
  setPaneDefaultTabs(project, paneId, tabs) {
    if (!paneId) {
      project.defaultTabs = tabs;
      return;
    }
    const pane = project.panes.find((p) => p.id === paneId);
    if (pane)
      pane.defaultTabs = tabs;
  }
  /** Save a pane's tabs as its default tab set. */
  saveDefaultTabs(project, paneId) {
    const group = this.getLiveGroup(this.paneKey(project.id, paneId));
    const tabs = group ? this.captureGroupTabs(group) : this.paneNotes(project, paneId).map((n) => ({ ...n }));
    this.setPaneDefaultTabs(project, paneId, tabs);
    void this.persistNow();
    this.refreshContentView();
    new import_obsidian2.Notice(`Saved ${tabs.length} default tab(s) for this pane.`);
  }
  /** Open a pane's saved default tabs as tabs in that pane. */
  async openDefaultTabs(project, paneId) {
    const defaults = this.paneDefaultTabs(project, paneId);
    if (defaults.length === 0) {
      new import_obsidian2.Notice("No default tabs saved for this pane.");
      return;
    }
    await this.showPane(project, paneId);
    for (const note of defaults) {
      const file = this.app.vault.getAbstractFileByPath(note.path);
      if (file instanceof import_obsidian2.TFile)
        await this.openNoteStateInActivePane(note, file);
    }
  }
  async deleteProject(project) {
    for (const [key, group] of [...this.projectGroups]) {
      if (key !== project.id && !key.startsWith(project.id + "::"))
        continue;
      const toClose = [];
      this.app.workspace.iterateRootLeaves((leaf) => {
        if (this.leafInGroup(leaf, group))
          toClose.push(leaf);
      });
      for (const leaf of toClose)
        leaf.detach();
      this.projectGroups.delete(key);
    }
    this.data.projects = this.data.projects.filter((p) => p.id !== project.id);
    if (this.data.activeProjectId === project.id) {
      this.data.activeProjectId = null;
    }
    await this.persistNow();
    this.refreshListView();
    this.refreshContentView();
  }
  // ---- Google Drive integration ----
  /** A vault folder path not currently in use (appends a number if taken). */
  uniqueVaultFolder(base) {
    let name = base;
    let i = 2;
    while (this.app.vault.getAbstractFileByPath(name))
      name = `${base} ${i++}`;
    return name;
  }
  /** Download a Drive folder into vaultDir, then create + open a linked project. */
  async createProjectFromDrive(opts) {
    new import_obsidian2.Notice("Downloading from Google Drive\u2026");
    let count = 0;
    try {
      count = await this.drive.downloadFolder(opts.folderId, opts.target);
    } catch (e) {
      new import_obsidian2.Notice(`Google Drive download failed: ${e.message}`);
      return;
    }
    const project = {
      id: genId(),
      name: opts.name,
      description: opts.description,
      folders: Array.from(/* @__PURE__ */ new Set([...opts.folders, opts.target])),
      notes: opts.notes,
      lastOpenNotes: [],
      lastClosedNotes: [],
      panes: [],
      activePaneId: null,
      pinned: [],
      driveFolderId: opts.folderId,
      driveLocalFolder: opts.target
    };
    this.data.projects.push(project);
    await this.persistNow();
    this.refreshListView();
    new import_obsidian2.Notice(`Imported ${count} file(s) into "${opts.target}".`);
    await this.openProject(project);
  }
  async uploadProjectToDrive(project) {
    if (!isDesktop()) {
      new import_obsidian2.Notice("Google Drive is desktop-only.");
      return;
    }
    if (!this.drive.isConnected()) {
      new import_obsidian2.Notice("Connect Google Drive in the plugin settings first.");
      return;
    }
    if (!project.driveFolderId || !project.driveLocalFolder) {
      new import_obsidian2.Notice("This project isn't linked to a Google Drive folder.");
      return;
    }
    new import_obsidian2.Notice(`Uploading "${project.name}" to Google Drive\u2026`);
    try {
      const n = await this.drive.uploadFolder(
        project.driveLocalFolder,
        project.driveFolderId
      );
      new import_obsidian2.Notice(`Uploaded ${n} file(s) to Google Drive.`);
    } catch (e) {
      new import_obsidian2.Notice(`Google Drive upload failed: ${e.message}`);
    }
  }
  /** Re-download the project's linked Drive folder into its local folder. */
  async downloadProjectFromDrive(project) {
    if (!isDesktop()) {
      new import_obsidian2.Notice("Google Drive is desktop-only.");
      return;
    }
    if (!this.drive.isConnected()) {
      new import_obsidian2.Notice("Connect Google Drive in the plugin settings first.");
      return;
    }
    if (!project.driveFolderId || !project.driveLocalFolder) {
      new import_obsidian2.Notice("This project isn't linked to a Google Drive folder.");
      return;
    }
    new import_obsidian2.Notice(`Downloading "${project.name}" from Google Drive\u2026`);
    try {
      const n = await this.drive.downloadFolder(
        project.driveFolderId,
        project.driveLocalFolder
      );
      new import_obsidian2.Notice(`Downloaded ${n} file(s) from Google Drive.`);
      this.refreshContentView();
    } catch (e) {
      new import_obsidian2.Notice(`Google Drive download failed: ${e.message}`);
    }
  }
  /** Upload a single file to its matching place in the project's Drive folder. */
  async uploadFileToDrive(project, file) {
    var _a;
    if (!isDesktop()) {
      new import_obsidian2.Notice("Google Drive is desktop-only.");
      return;
    }
    if (!this.drive.isConnected()) {
      new import_obsidian2.Notice("Connect Google Drive in the plugin settings first.");
      return;
    }
    if (!project.driveFolderId) {
      new import_obsidian2.Notice("This project isn't linked to a Google Drive folder.");
      return;
    }
    const local = (_a = project.driveLocalFolder) != null ? _a : "";
    let dirParts = [];
    if (local && file.path.startsWith(local + "/")) {
      const parts = file.path.slice(local.length + 1).split("/");
      parts.pop();
      dirParts = parts;
    }
    new import_obsidian2.Notice(`Uploading "${file.name}" to Google Drive\u2026`);
    try {
      await this.drive.uploadSingleFile(project.driveFolderId, file, dirParts);
      new import_obsidian2.Notice(`Uploaded "${file.name}" to Google Drive.`);
    } catch (e) {
      new import_obsidian2.Notice(`Google Drive upload failed: ${e.message}`);
    }
  }
};
var ProjectListView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.reordering = false;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_PROJECT_LIST;
  }
  getDisplayText() {
    return "Projects";
  }
  getIcon() {
    return "folder-kanban";
  }
  async onOpen() {
    this.render();
  }
  render() {
    const c = this.contentEl;
    c.empty();
    c.addClass("recent-view-list");
    const header = c.createDiv({ cls: "rv-header" });
    const titleWrap = header.createDiv({ cls: "rv-header-title-wrap" });
    titleWrap.createEl("span", { cls: "rv-header-title", text: "Projects" });
    const menuBtn = titleWrap.createEl("button", {
      cls: "rv-icon-btn rv-header-menu"
    });
    if (this.reordering)
      menuBtn.addClass("is-active");
    (0, import_obsidian2.setIcon)(menuBtn, "more-vertical");
    menuBtn.setAttribute("aria-label", "Projects options");
    menuBtn.onclick = (e) => {
      e.stopPropagation();
      const menu = new import_obsidian2.Menu();
      menu.addItem(
        (i) => i.setTitle(this.reordering ? "Done reordering" : "Reorder projects").setIcon(this.reordering ? "check" : "arrow-up-down").setDisabled(this.plugin.data.projects.length < 2).onClick(() => {
          this.reordering = !this.reordering;
          this.render();
        })
      );
      showMenu(menu, e, this.contentEl, menuBtn);
    };
    const headerActions = header.createDiv({ cls: "rv-header-actions" });
    const backBtn = headerActions.createEl("button", {
      cls: "rv-icon-btn rv-back-btn"
    });
    (0, import_obsidian2.setIcon)(backBtn, "arrow-left");
    backBtn.setAttribute("aria-label", "Back to last project");
    backBtn.disabled = !this.plugin.canGoBack();
    backBtn.onclick = () => void this.plugin.goBack();
    const addBtn = headerActions.createEl("button", {
      cls: "rv-new-btn",
      text: "+ New"
    });
    addBtn.onclick = () => new ProjectEditModal(this.plugin.app, this.plugin, null).open();
    const list = c.createDiv({ cls: "rv-project-list" });
    if (this.reordering)
      list.addClass("rv-reordering");
    if (this.plugin.data.projects.length === 0) {
      this.reordering = false;
      list.createDiv({
        cls: "rv-empty",
        text: 'No projects yet. Click "+ New" to create one.'
      });
      return;
    }
    for (const project of this.plugin.data.projects) {
      const box = list.createDiv({ cls: "rv-project-box" });
      if (project.id === this.plugin.data.activeProjectId) {
        box.addClass("is-active");
      }
      if (this.reordering)
        box.dataset.rvId = project.id;
      const info = box.createDiv({ cls: "rv-project-info" });
      info.createDiv({ cls: "rv-project-name", text: project.name });
      if (project.description) {
        info.createDiv({ cls: "rv-project-desc", text: project.description });
      }
      const actions = box.createDiv({ cls: "rv-project-actions" });
      const menuBtn2 = actions.createEl("button", { cls: "rv-icon-btn" });
      (0, import_obsidian2.setIcon)(menuBtn2, "more-vertical");
      menuBtn2.setAttribute("aria-label", "Project options");
      menuBtn2.onclick = (e) => {
        e.stopPropagation();
        const menu = new import_obsidian2.Menu();
        menu.addItem(
          (item) => item.setTitle("Edit project").setIcon("pencil").onClick(
            () => new ProjectEditModal(this.plugin.app, this.plugin, project).open()
          )
        );
        menu.addItem(
          (item) => item.setTitle("Add folder to project\u2026").setIcon("folder-plus").onClick(
            () => new FolderSuggestModal(
              this.plugin.app,
              (folder) => void this.plugin.addFolderToProject(project, folder)
            ).open()
          )
        );
        menu.addItem(
          (item) => item.setTitle("Add note to project\u2026").setIcon("file-plus").onClick(
            () => new FileSuggestModal(
              this.plugin.app,
              (file) => void this.plugin.addNoteToProject(project, file)
            ).open()
          )
        );
        if (project.driveFolderId) {
          menu.addItem(
            (item) => item.setTitle("Download from Google Drive").setIcon("cloud-download").onClick(() => void this.plugin.downloadProjectFromDrive(project))
          );
          menu.addItem(
            (item) => item.setTitle("Upload to Google Drive").setIcon("cloud-upload").onClick(() => void this.plugin.uploadProjectToDrive(project))
          );
        }
        menu.addItem(
          (item) => item.setTitle("Delete project").setIcon("trash-2").onClick(
            () => new ConfirmModal(
              this.plugin.app,
              `Delete project "${project.name}"?`,
              () => void this.plugin.deleteProject(project)
            ).open()
          )
        );
        showMenu(menu, e, this.contentEl, menuBtn2);
      };
      box.onclick = () => {
        if (this.reordering)
          return;
        void this.plugin.openProject(project);
      };
    }
    if (this.reordering) {
      enableReorder(list, (ids) => void this.plugin.setProjectOrder(ids));
    }
  }
};
var ProjectContentView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.reordering = false;
    this.panesReordering = false;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_PROJECT_CONTENT;
  }
  getDisplayText() {
    return "Project contents";
  }
  getIcon() {
    return "list-tree";
  }
  async onOpen() {
    this.render();
  }
  render() {
    var _a;
    const c = this.contentEl;
    c.empty();
    c.addClass("recent-view-content");
    const header = c.createDiv({ cls: "rv-content-header" });
    const info = header.createDiv({ cls: "rv-content-headinfo" });
    const project = this.plugin.getActiveProject();
    info.createEl("h4", {
      cls: "rv-content-title",
      text: project ? project.name : "Project contents"
    });
    const menuBtn = header.createEl("button", {
      cls: "rv-icon-btn rv-content-menu"
    });
    (0, import_obsidian2.setIcon)(menuBtn, "more-vertical");
    menuBtn.setAttribute("aria-label", "More options");
    menuBtn.onclick = (e) => {
      const menu = new import_obsidian2.Menu();
      if (project) {
        menu.addItem(
          (item) => item.setTitle("New pane").setIcon("plus").onClick(
            () => new PromptModal(
              this.plugin.app,
              "New pane",
              `Pane ${project.panes.length + 1}`,
              (name) => void this.plugin.addPane(project, name)
            ).open()
          )
        );
      }
      if (project == null ? void 0 : project.driveFolderId) {
        menu.addItem(
          (item) => item.setTitle("Download from Google Drive").setIcon("cloud-download").onClick(() => void this.plugin.downloadProjectFromDrive(project))
        );
        menu.addItem(
          (item) => item.setTitle("Upload to Google Drive").setIcon("cloud-upload").onClick(() => void this.plugin.uploadProjectToDrive(project))
        );
      }
      menu.addItem(
        (item) => item.setTitle("Refresh").setIcon("refresh-cw").onClick(() => this.render())
      );
      showMenu(menu, e, this.contentEl, menuBtn);
    };
    if (!project) {
      c.createDiv({
        cls: "rv-empty",
        text: "Open a project to see its folders and notes."
      });
      return;
    }
    if (project.description) {
      info.createDiv({ cls: "rv-project-desc", text: project.description });
    }
    this.renderPanes(c, project);
    const pinnedFiles = ((_a = project.pinned) != null ? _a : []).map((path) => this.plugin.app.vault.getAbstractFileByPath(path)).filter((f) => f instanceof import_obsidian2.TFile);
    if (pinnedFiles.length > 0) {
      const section = c.createDiv({ cls: "rv-folder-section rv-pinned-section" });
      if (this.reordering)
        section.addClass("rv-reordering");
      const head = section.createDiv({ cls: "rv-folder-head" });
      (0, import_obsidian2.setIcon)(head.createSpan({ cls: "rv-folder-icon" }), "pin");
      head.createSpan({ text: "Pinned" });
      const menuBtn2 = head.createEl("button", {
        cls: "rv-icon-btn rv-head-menu"
      });
      (0, import_obsidian2.setIcon)(menuBtn2, "more-vertical");
      menuBtn2.setAttribute("aria-label", "More options");
      menuBtn2.onclick = (e) => {
        e.stopPropagation();
        const menu = new import_obsidian2.Menu();
        menu.addItem(
          (i) => i.setTitle(this.reordering ? "Done reordering" : "Reorder").setIcon(this.reordering ? "check" : "arrow-up-down").onClick(() => {
            this.reordering = !this.reordering;
            this.render();
          })
        );
        showMenu(menu, e, this.contentEl, menuBtn2);
      };
      const fileList = section.createDiv({ cls: "rv-file-list" });
      for (const file of pinnedFiles) {
        const item = this.renderFileItem(fileList, file);
        if (this.reordering)
          item.dataset.rvId = file.path;
      }
      if (this.reordering) {
        enableReorder(
          fileList,
          (ids) => void this.plugin.setPinnedOrder(project, ids)
        );
      }
    } else if (this.reordering) {
      this.reordering = false;
    }
    for (const folderPath of project.folders) {
      const folder = this.plugin.app.vault.getAbstractFileByPath(folderPath);
      if (folder instanceof import_obsidian2.TFolder) {
        this.renderFolderSection(c, project, folder, 0, folderPath);
      } else {
        const section = c.createDiv({ cls: "rv-folder-section" });
        const head = section.createDiv({ cls: "rv-folder-head" });
        (0, import_obsidian2.setIcon)(head.createSpan({ cls: "rv-folder-icon" }), "folder");
        head.createSpan({ text: folderPath });
        const menuBtn2 = head.createEl("button", {
          cls: "rv-icon-btn rv-head-menu"
        });
        (0, import_obsidian2.setIcon)(menuBtn2, "more-vertical");
        menuBtn2.setAttribute("aria-label", "Folder options");
        menuBtn2.onclick = (e) => {
          e.stopPropagation();
          const menu = new import_obsidian2.Menu();
          menu.addItem(
            (i) => i.setTitle("Remove from project").setIcon("x").onClick(
              () => void this.plugin.removeFolderFromProject(project, folderPath)
            )
          );
          showMenu(menu, e, this.contentEl, menuBtn2);
        };
        section.createDiv({ cls: "rv-empty-sm", text: "Folder not found" });
      }
    }
    if (project.notes.length > 0) {
      const section = c.createDiv({ cls: "rv-folder-section" });
      const head = section.createDiv({ cls: "rv-folder-head" });
      (0, import_obsidian2.setIcon)(head.createSpan({ cls: "rv-folder-icon" }), "file-text");
      head.createSpan({ text: "Notes" });
      const fileList = section.createDiv({ cls: "rv-file-list" });
      const looseNotes = project.notes.map((path) => this.plugin.app.vault.getAbstractFileByPath(path)).filter((f) => f instanceof import_obsidian2.TFile).sort((a, b) => a.basename.localeCompare(b.basename));
      for (const file of looseNotes)
        this.renderFileItem(fileList, file);
    }
  }
  /** List the project's panes (main + named) when it has named panes. */
  renderPanes(c, project) {
    var _a;
    if (!project.panes || project.panes.length === 0) {
      this.panesReordering = false;
      return;
    }
    const activePaneId = (_a = project.activePaneId) != null ? _a : null;
    const section = c.createDiv({ cls: "rv-folder-section rv-panes-section" });
    if (this.panesReordering)
      section.addClass("rv-reordering");
    const head = section.createDiv({ cls: "rv-folder-head" });
    (0, import_obsidian2.setIcon)(head.createSpan({ cls: "rv-folder-icon" }), "layout-grid");
    head.createSpan({ text: "Panes" });
    const menuBtn = head.createEl("button", { cls: "rv-icon-btn rv-head-menu" });
    if (this.panesReordering)
      menuBtn.addClass("is-active");
    (0, import_obsidian2.setIcon)(menuBtn, "more-vertical");
    menuBtn.setAttribute("aria-label", "Panes options");
    menuBtn.onclick = (e) => {
      e.stopPropagation();
      const menu = new import_obsidian2.Menu();
      menu.addItem(
        (i) => i.setTitle(this.panesReordering ? "Done reordering" : "Reorder panes").setIcon(this.panesReordering ? "check" : "arrow-up-down").setDisabled(project.panes.length < 2).onClick(() => {
          this.panesReordering = !this.panesReordering;
          this.render();
        })
      );
      showMenu(menu, e, this.contentEl, menuBtn);
    };
    const list = section.createDiv({ cls: "rv-file-list" });
    this.renderPaneItem(list, project, null, "Main", activePaneId === null);
    for (const pane of project.panes) {
      const item = this.renderPaneItem(
        list,
        project,
        pane.id,
        pane.name,
        activePaneId === pane.id
      );
      if (this.panesReordering)
        item.dataset.rvId = pane.id;
    }
    if (this.panesReordering) {
      enableReorder(list, (ids) => void this.plugin.setPaneOrder(project, ids));
    }
  }
  renderPaneItem(list, project, paneId, name, isActive) {
    const item = list.createDiv({ cls: "rv-file-item rv-pane-item" });
    if (isActive)
      item.addClass("is-active");
    (0, import_obsidian2.setIcon)(
      item.createSpan({ cls: "rv-file-icon" }),
      paneId ? "gallery-vertical" : "home"
    );
    item.createSpan({ cls: "rv-file-name", text: name });
    item.onclick = () => {
      if (this.panesReordering)
        return;
      void this.plugin.showPane(project, paneId);
    };
    const menuBtn = item.createEl("button", { cls: "rv-icon-btn rv-item-menu" });
    (0, import_obsidian2.setIcon)(menuBtn, "more-vertical");
    menuBtn.setAttribute("aria-label", "Pane options");
    menuBtn.onclick = (e) => {
      e.stopPropagation();
      const menu = new import_obsidian2.Menu();
      const lastClosed = this.plugin.lastClosedNote(project, paneId);
      menu.addItem(
        (i) => i.setTitle("Open last closed tab").setIcon("undo-2").setDisabled(!lastClosed).onClick(
          () => void this.plugin.openLastClosedInPane(project, paneId)
        )
      );
      menu.addItem(
        (i) => i.setTitle("Open folder\u2026").setIcon("folder-open").onClick(
          () => new FolderSuggestModal(
            this.plugin.app,
            (folder) => void this.plugin.openFolderInPane(project, paneId, folder),
            this.plugin.projectFolders(project)
          ).open()
        )
      );
      menu.addItem(
        (i) => i.setTitle("Open note\u2026").setIcon("file").onClick(
          () => new FileSuggestModal(
            this.plugin.app,
            (file) => void this.plugin.openNoteInPane(project, paneId, file),
            this.plugin.projectFiles(project)
          ).open()
        )
      );
      menu.addItem(
        (i) => i.setTitle("Browse\u2026").setIcon("list-tree").onClick(
          () => new ProjectTreeModal(
            this.plugin.app,
            project,
            (folder) => void this.plugin.openFolderInPane(project, paneId, folder),
            (file) => void this.plugin.openNoteInPane(project, paneId, file)
          ).open()
        )
      );
      menu.addSeparator();
      menu.addItem(
        (i) => i.setTitle("Save current tabs as default").setIcon("save").onClick(() => this.plugin.saveDefaultTabs(project, paneId))
      );
      menu.addItem(
        (i) => i.setTitle("Open default tabs").setIcon("layout-list").setDisabled(this.plugin.paneHasDefaultTabs(project, paneId) === false).onClick(() => void this.plugin.openDefaultTabs(project, paneId))
      );
      if (paneId) {
        menu.addSeparator();
        menu.addItem(
          (i) => i.setTitle("Rename").setIcon("pencil").onClick(
            () => new PromptModal(
              this.plugin.app,
              "Rename pane",
              name,
              (v) => void this.plugin.renamePaneItem(project, paneId, v)
            ).open()
          )
        );
        menu.addItem(
          (i) => i.setTitle("Delete pane").setIcon("trash-2").onClick(
            () => new ConfirmModal(
              this.plugin.app,
              `Delete pane "${name}"?`,
              () => void this.plugin.deletePaneItem(project, paneId)
            ).open()
          )
        );
      }
      showMenu(menu, e, this.contentEl, menuBtn);
    };
    return item;
  }
  renderFileItem(container, file) {
    const item = container.createDiv({ cls: "rv-file-item" });
    (0, import_obsidian2.setIcon)(item.createSpan({ cls: "rv-file-icon" }), "file");
    item.createSpan({ cls: "rv-file-name", text: file.basename });
    item.onclick = () => this.openOrFocus(file);
    const menuBtn = item.createEl("button", { cls: "rv-icon-btn rv-item-menu" });
    (0, import_obsidian2.setIcon)(menuBtn, "more-vertical");
    menuBtn.setAttribute("aria-label", "More options");
    menuBtn.onclick = (e) => {
      e.stopPropagation();
      this.showFileMenu(e, file, menuBtn);
    };
    return item;
  }
  /**
   * Render a folder's notes (sorted), then each subfolder's notes below a
   * separator labelled with the subfolder name (recursively). Returns the total
   * number of notes rendered.
   */
  /**
   * Render a folder as a section (header + notes), recursing into subfolders
   * which are rendered the same way (indented). projectFolderPath is set only
   * for a project's top-level folders (enables "Remove from project").
   */
  renderFolderSection(container, project, folder, depth, projectFolderPath) {
    const section = container.createDiv({ cls: "rv-folder-section" });
    if (depth > 0)
      section.style.paddingLeft = `${depth * 14}px`;
    const head = section.createDiv({ cls: "rv-folder-head" });
    (0, import_obsidian2.setIcon)(head.createSpan({ cls: "rv-folder-icon" }), "folder");
    head.createSpan({ text: folder.name });
    const menuBtn = head.createEl("button", {
      cls: "rv-icon-btn rv-head-menu"
    });
    (0, import_obsidian2.setIcon)(menuBtn, "more-vertical");
    menuBtn.setAttribute("aria-label", "Folder options");
    menuBtn.onclick = (e) => {
      e.stopPropagation();
      const menu = new import_obsidian2.Menu();
      menu.addItem(
        (i) => i.setTitle("New note").setIcon("file-plus").onClick(() => void this.plugin.createNoteInFolder(folder))
      );
      menu.addSeparator();
      menu.addItem(
        (i) => i.setTitle("Rename").setIcon("pencil").onClick(() => new RenameModal(this.plugin.app, folder).open())
      );
      if (projectFolderPath) {
        menu.addItem(
          (i) => i.setTitle("Remove from project").setIcon("x").onClick(
            () => void this.plugin.removeFolderFromProject(project, projectFolderPath)
          )
        );
      }
      showMenu(menu, e, this.contentEl, menuBtn);
    };
    const fileList = section.createDiv({ cls: "rv-file-list" });
    const children = [...folder.children];
    const files = children.filter((c) => c instanceof import_obsidian2.TFile && c.extension === "md").sort((a, b) => a.basename.localeCompare(b.basename));
    const subfolders = children.filter((c) => c instanceof import_obsidian2.TFolder && countMarkdown(c) > 0).sort((a, b) => a.name.localeCompare(b.name));
    for (const f of files)
      this.renderFileItem(fileList, f);
    for (const sub of subfolders) {
      this.renderFolderSection(fileList, project, sub, depth + 1, null);
    }
    if (files.length === 0 && subfolders.length === 0) {
      fileList.createDiv({ cls: "rv-empty-sm", text: "No notes" });
    }
  }
  showFileMenu(e, file, btn) {
    var _a;
    const project = this.plugin.getActiveProject();
    const menu = new import_obsidian2.Menu();
    if (project) {
      const pinned = ((_a = project.pinned) != null ? _a : []).includes(file.path);
      menu.addItem(
        (i) => i.setTitle(pinned ? "Unpin from top" : "Pin to top").setIcon(pinned ? "pin-off" : "pin").onClick(() => void this.plugin.togglePin(project, file.path))
      );
    }
    menu.addItem(
      (i) => i.setTitle("Rename").setIcon("pencil").onClick(() => new RenameModal(this.plugin.app, file).open())
    );
    if (project == null ? void 0 : project.driveFolderId) {
      menu.addItem(
        (i) => i.setTitle("Upload to Google Drive").setIcon("cloud-upload").onClick(() => void this.plugin.uploadFileToDrive(project, file))
      );
    }
    menu.addSeparator();
    menu.addItem(
      (i) => i.setTitle("Delete").setIcon("trash-2").onClick(
        () => new ConfirmModal(
          this.plugin.app,
          `Delete "${file.basename}"?`,
          () => void this.plugin.app.fileManager.trashFile(file)
        ).open()
      )
    );
    showMenu(menu, e, this.contentEl, btn);
  }
  openOrFocus(file) {
    const { workspace } = this.plugin.app;
    const group = this.plugin.getActiveGroup();
    const existing = this.findLeafForFile(file, group);
    if (existing) {
      workspace.setActiveLeaf(existing, { focus: true });
      workspace.revealLeaf(existing);
      return;
    }
    if (group)
      this.plugin.focusActiveGroup();
    void workspace.getLeaf("tab").openFile(file);
  }
  findLeafForFile(file, group) {
    let found = null;
    this.plugin.app.workspace.iterateRootLeaves((leaf) => {
      var _a;
      if (found)
        return;
      if (group && !this.plugin.leafInGroup(leaf, group))
        return;
      if (((_a = leaf.getViewState().state) == null ? void 0 : _a.file) === file.path)
        found = leaf;
    });
    return found;
  }
};
var RenameModal = class extends import_obsidian2.Modal {
  constructor(app, item) {
    super(app);
    this.item = item;
    this.isFile = item instanceof import_obsidian2.TFile;
    this.value = item instanceof import_obsidian2.TFile ? item.basename : item.name;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("recent-view-modal");
    contentEl.createEl("h3", {
      text: this.isFile ? "Rename note" : "Rename folder"
    });
    let inputEl = null;
    new import_obsidian2.Setting(contentEl).setName("New name").addText((t) => {
      t.setValue(this.value).onChange((v) => this.value = v);
      inputEl = t.inputEl;
      t.inputEl.addEventListener("keydown", (e) => {
        if (e.key === "Enter") {
          e.preventDefault();
          void this.doRename();
        }
      });
    });
    const footer = contentEl.createDiv({ cls: "rv-modal-footer" });
    const ok = footer.createEl("button", { cls: "mod-cta", text: "Rename" });
    ok.onclick = () => void this.doRename();
    const cancel = footer.createEl("button", { text: "Cancel" });
    cancel.onclick = () => this.close();
    window.setTimeout(() => {
      inputEl == null ? void 0 : inputEl.focus();
      inputEl == null ? void 0 : inputEl.select();
    }, 0);
  }
  async doRename() {
    var _a;
    const name = this.value.trim();
    if (!name) {
      new import_obsidian2.Notice("Name is required");
      return;
    }
    const parent = (_a = this.item.parent) == null ? void 0 : _a.path;
    const dir = parent && parent !== "/" ? `${parent}/` : "";
    const ext = this.item instanceof import_obsidian2.TFile ? `.${this.item.extension}` : "";
    const newPath = `${dir}${name}${ext}`;
    if (newPath === this.item.path) {
      this.close();
      return;
    }
    try {
      await this.app.fileManager.renameFile(this.item, newPath);
    } catch (e) {
      new import_obsidian2.Notice(`Rename failed: ${e.message}`);
      return;
    }
    this.close();
  }
};
function countMarkdown(folder) {
  let n = 0;
  for (const child of folder.children) {
    if (child instanceof import_obsidian2.TFolder)
      n += countMarkdown(child);
    else if (child instanceof import_obsidian2.TFile && child.extension === "md")
      n++;
  }
  return n;
}
var ProjectEditModal = class extends import_obsidian2.Modal {
  constructor(app, plugin, project) {
    var _a, _b, _c, _d;
    super(app);
    this.driveLink = "";
    this.driveTarget = "";
    this.driveFolderName = "";
    this.plugin = plugin;
    this.project = project;
    this.name = (_a = project == null ? void 0 : project.name) != null ? _a : "";
    this.description = (_b = project == null ? void 0 : project.description) != null ? _b : "";
    this.folders = [...(_c = project == null ? void 0 : project.folders) != null ? _c : []];
    this.notes = [...(_d = project == null ? void 0 : project.notes) != null ? _d : []];
  }
  onOpen() {
    this.renderForm();
  }
  renderForm() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("recent-view-modal");
    contentEl.createEl("h3", {
      text: this.project ? "Edit project" : "New project"
    });
    new import_obsidian2.Setting(contentEl).setName("Name").addText(
      (t) => t.setPlaceholder("Project name").setValue(this.name).onChange((v) => this.name = v)
    );
    new import_obsidian2.Setting(contentEl).setName("Description").addTextArea(
      (t) => t.setPlaceholder("What is this project about?").setValue(this.description).onChange((v) => this.description = v)
    );
    new import_obsidian2.Setting(contentEl).setName("Folders").setDesc("Folders included in this project").addButton(
      (b) => b.setButtonText("Add folder").onClick(() => {
        new FolderSuggestModal(this.app, (folder) => {
          if (!this.folders.includes(folder.path)) {
            this.folders.push(folder.path);
          }
          this.renderForm();
        }).open();
      })
    );
    this.renderChipList(contentEl, this.folders, (path) => {
      this.folders = this.folders.filter((x) => x !== path);
      this.renderForm();
    });
    new import_obsidian2.Setting(contentEl).setName("Notes").setDesc("Specific notes included in this project").addButton(
      (b) => b.setButtonText("Add note").onClick(() => {
        new FileSuggestModal(this.app, (file) => {
          if (!this.notes.includes(file.path))
            this.notes.push(file.path);
          this.renderForm();
        }).open();
      })
    );
    this.renderChipList(contentEl, this.notes, (path) => {
      this.notes = this.notes.filter((x) => x !== path);
      this.renderForm();
    });
    if (!this.project)
      this.renderDriveSection(contentEl);
    const footer = contentEl.createDiv({ cls: "rv-modal-footer" });
    const saveBtn = footer.createEl("button", {
      cls: "mod-cta",
      text: "Save"
    });
    saveBtn.onclick = () => void this.save();
    const cancelBtn = footer.createEl("button", { text: "Cancel" });
    cancelBtn.onclick = () => this.close();
  }
  renderDriveSection(contentEl) {
    new import_obsidian2.Setting(contentEl).setName("Import from Google Drive").setHeading();
    contentEl.createEl("p", {
      cls: "setting-item-description",
      text: "Paste a Google Drive folder share link to download its files into a folder. Set up Google Drive in plugin settings first. Desktop only."
    });
    contentEl.createEl("p", {
      cls: "setting-item-description",
      text: "Note: download is additive/overwrite \u2014 it writes the Drive files into the local folder (updating existing ones), but it does not delete local files that were removed on Drive. Same one-way model as upload."
    });
    new import_obsidian2.Setting(contentEl).setName("Share link").addText(
      (t) => t.setPlaceholder("https://drive.google.com/drive/folders/\u2026").setValue(this.driveLink).onChange((v) => this.driveLink = v)
    ).addButton(
      (b) => b.setButtonText("Fetch name").onClick(async () => {
        const id = parseDriveFolderId(this.driveLink);
        if (!id) {
          new import_obsidian2.Notice("Couldn't find a Google Drive folder in that link.");
          return;
        }
        if (!this.plugin.drive.isConnected()) {
          new import_obsidian2.Notice("Connect Google Drive in plugin settings first.");
          return;
        }
        try {
          this.driveFolderName = await this.plugin.drive.getFolderName(id);
          if (!this.name.trim())
            this.name = this.driveFolderName;
          if (!this.driveTarget.trim()) {
            this.driveTarget = this.plugin.uniqueVaultFolder(
              sanitizeVaultName(this.driveFolderName)
            );
          }
          this.renderForm();
        } catch (e) {
          new import_obsidian2.Notice(`Google Drive: ${e.message}`);
        }
      })
    );
    new import_obsidian2.Setting(contentEl).setName("Download to folder").setDesc("New folder name, or choose an existing folder").addText(
      (t) => t.setPlaceholder("Folder name (defaults to the Drive folder name)").setValue(this.driveTarget).onChange((v) => this.driveTarget = v)
    ).addButton(
      (b) => b.setButtonText("Choose").onClick(
        () => new FolderSuggestModal(this.app, (folder) => {
          this.driveTarget = folder.path === "/" ? "" : folder.path;
          this.renderForm();
        }).open()
      )
    );
  }
  renderChipList(parent, items, onRemove) {
    if (items.length === 0)
      return;
    const list = parent.createDiv({ cls: "rv-modal-list" });
    for (const path of items) {
      const row = list.createDiv({ cls: "rv-modal-row" });
      row.createSpan({ cls: "rv-modal-row-path", text: path });
      const rm = row.createEl("button", { cls: "rv-icon-btn" });
      (0, import_obsidian2.setIcon)(rm, "x");
      rm.onclick = () => onRemove(path);
    }
  }
  async save() {
    if (!this.name.trim()) {
      new import_obsidian2.Notice("Project name is required");
      return;
    }
    if (!this.project && this.driveLink.trim()) {
      if (!isDesktop()) {
        new import_obsidian2.Notice("Google Drive is desktop-only.");
        return;
      }
      if (!this.plugin.drive.isConnected()) {
        new import_obsidian2.Notice("Connect Google Drive in plugin settings first.");
        return;
      }
      const folderId = parseDriveFolderId(this.driveLink);
      if (!folderId) {
        new import_obsidian2.Notice("Couldn't find a Google Drive folder in that link.");
        return;
      }
      let target = this.driveTarget.trim();
      if (!target) {
        let driveName = this.driveFolderName;
        if (!driveName) {
          try {
            driveName = await this.plugin.drive.getFolderName(folderId);
          } catch (e) {
            new import_obsidian2.Notice(`Google Drive: ${e.message}`);
            return;
          }
        }
        target = this.plugin.uniqueVaultFolder(sanitizeVaultName(driveName));
      }
      this.close();
      await this.plugin.createProjectFromDrive({
        name: this.name.trim(),
        description: this.description,
        folders: this.folders,
        notes: this.notes,
        folderId,
        target
      });
      return;
    }
    if (this.project) {
      this.project.name = this.name.trim();
      this.project.description = this.description;
      this.project.folders = this.folders;
      this.project.notes = this.notes;
    } else {
      this.plugin.data.projects.push({
        id: genId(),
        name: this.name.trim(),
        description: this.description,
        folders: this.folders,
        notes: this.notes,
        lastOpenNotes: [],
        lastClosedNotes: [],
        panes: [],
        activePaneId: null,
        pinned: []
      });
    }
    await this.plugin.persistNow();
    this.plugin.refreshListView();
    this.plugin.refreshContentView();
    this.close();
  }
};
var FolderSuggestModal = class extends import_obsidian2.FuzzySuggestModal {
  constructor(app, onChoose, items) {
    super(app);
    this.onChoose = onChoose;
    this.items = items;
    this.setPlaceholder("Pick a folder");
  }
  getItems() {
    if (this.items)
      return this.items;
    const folders = [];
    import_obsidian2.Vault.recurseChildren(this.app.vault.getRoot(), (f) => {
      if (f instanceof import_obsidian2.TFolder)
        folders.push(f);
    });
    return folders;
  }
  getItemText(item) {
    return item.path === "/" ? "/ (vault root)" : item.path;
  }
  onChooseItem(item) {
    this.onChoose(item);
  }
};
var FileSuggestModal = class extends import_obsidian2.FuzzySuggestModal {
  constructor(app, onChoose, items) {
    super(app);
    this.onChoose = onChoose;
    this.items = items;
    this.setPlaceholder("Pick a note");
  }
  getItems() {
    var _a;
    return (_a = this.items) != null ? _a : this.app.vault.getMarkdownFiles();
  }
  getItemText(item) {
    return item.path;
  }
  onChooseItem(item) {
    this.onChoose(item);
  }
};
var ProjectTreeModal = class extends import_obsidian2.Modal {
  constructor(app, project, onFolder, onFile) {
    super(app);
    this.project = project;
    this.onFolder = onFolder;
    this.onFile = onFile;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("recent-view-modal");
    contentEl.createEl("h3", { text: "Browse project" });
    contentEl.createDiv({
      cls: "rv-empty-sm",
      text: "Choose a folder to open all of its notes, or choose a note to open just that note."
    });
    const tree = contentEl.createDiv({ cls: "rv-tree-picker" });
    const folders = this.topLevelProjectFolders();
    for (const folder of folders)
      this.renderFolder(tree, folder, 0);
    const looseNotes = this.looseProjectNotes();
    if (looseNotes.length > 0) {
      const section = tree.createDiv({ cls: "rv-tree-section" });
      section.createSpan({ text: "Notes" });
      for (const file of looseNotes)
        this.renderFile(tree, file, 1);
    }
    if (folders.length === 0 && looseNotes.length === 0) {
      tree.createDiv({ cls: "rv-empty", text: "No project folders or notes." });
    }
  }
  topLevelProjectFolders() {
    const folders = this.project.folders.map((path) => this.app.vault.getAbstractFileByPath(path)).filter((f) => f instanceof import_obsidian2.TFolder).sort((a, b) => a.path.localeCompare(b.path));
    return folders.filter(
      (folder, index) => folders.findIndex((other) => folder.path === other.path) === index && !folders.some(
        (other) => other.path !== folder.path && folder.path.startsWith(other.path + "/")
      )
    );
  }
  looseProjectNotes() {
    const insideProjectFolder = (file) => this.project.folders.some(
      (folderPath) => file.path === folderPath || file.path.startsWith(folderPath + "/")
    );
    return this.project.notes.map((path) => this.app.vault.getAbstractFileByPath(path)).filter((f) => f instanceof import_obsidian2.TFile && !insideProjectFolder(f)).sort((a, b) => a.path.localeCompare(b.path));
  }
  renderFolder(container, folder, depth) {
    const row = container.createDiv({ cls: "rv-tree-row rv-tree-folder" });
    row.style.paddingLeft = `${8 + depth * 14}px`;
    (0, import_obsidian2.setIcon)(row.createSpan({ cls: "rv-file-icon" }), "folder");
    row.createSpan({ cls: "rv-file-name", text: folder.name || "/" });
    row.setAttribute("aria-label", `Open all notes in ${folder.path}`);
    row.onclick = () => {
      this.onFolder(folder);
      this.close();
    };
    const children = [...folder.children];
    const files = children.filter((child) => child instanceof import_obsidian2.TFile && child.extension === "md").sort((a, b) => a.basename.localeCompare(b.basename));
    const folders = children.filter((child) => child instanceof import_obsidian2.TFolder).sort((a, b) => a.name.localeCompare(b.name));
    for (const file of files)
      this.renderFile(container, file, depth + 1);
    for (const child of folders)
      this.renderFolder(container, child, depth + 1);
  }
  renderFile(container, file, depth) {
    const row = container.createDiv({ cls: "rv-tree-row rv-tree-file" });
    row.style.paddingLeft = `${8 + depth * 14}px`;
    (0, import_obsidian2.setIcon)(row.createSpan({ cls: "rv-file-icon" }), "file");
    row.createSpan({ cls: "rv-file-name", text: file.basename });
    row.setAttribute("aria-label", `Open ${file.path}`);
    row.onclick = () => {
      this.onFile(file);
      this.close();
    };
  }
};
var ConfirmModal = class extends import_obsidian2.Modal {
  constructor(app, message, onConfirm) {
    super(app);
    this.message = message;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("p", { text: this.message });
    const footer = contentEl.createDiv({ cls: "rv-modal-footer" });
    const yes = footer.createEl("button", { cls: "mod-warning", text: "Delete" });
    yes.onclick = () => {
      this.onConfirm();
      this.close();
    };
    const no = footer.createEl("button", { text: "Cancel" });
    no.onclick = () => this.close();
  }
};
var PromptModal = class extends import_obsidian2.Modal {
  constructor(app, titleText, defaultValue, onSubmit) {
    super(app);
    this.titleText = titleText;
    this.value = defaultValue;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("recent-view-modal");
    contentEl.createEl("h3", { text: this.titleText });
    let inputEl = null;
    new import_obsidian2.Setting(contentEl).setName("Name").addText((t) => {
      t.setValue(this.value).onChange((v) => this.value = v);
      inputEl = t.inputEl;
      t.inputEl.addEventListener("keydown", (e) => {
        if (e.key === "Enter") {
          e.preventDefault();
          this.submit();
        }
      });
    });
    const footer = contentEl.createDiv({ cls: "rv-modal-footer" });
    const ok = footer.createEl("button", { cls: "mod-cta", text: "OK" });
    ok.onclick = () => this.submit();
    const cancel = footer.createEl("button", { text: "Cancel" });
    cancel.onclick = () => this.close();
    window.setTimeout(() => {
      inputEl == null ? void 0 : inputEl.focus();
      inputEl == null ? void 0 : inputEl.select();
    }, 0);
  }
  submit() {
    const v = this.value.trim();
    if (!v) {
      new import_obsidian2.Notice("Name is required");
      return;
    }
    this.onSubmit(v);
    this.close();
  }
};
var RecentViewSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Data note path").setDesc(
      "Vault-relative path of the note that stores this vault's projects. Stored inside the vault so the data is per-vault and travels with it."
    ).addText(
      (text) => text.setPlaceholder(DEFAULT_SETTINGS.dataNotePath).setValue(this.plugin.settings.dataNotePath).onChange(async (value) => {
        const next = value.trim() || DEFAULT_SETTINGS.dataNotePath;
        if (next === this.plugin.settings.dataNotePath)
          return;
        this.plugin.settings.dataNotePath = next;
        await this.plugin.persistNow();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Google Drive").setHeading();
    containerEl.createEl("p", {
      cls: "setting-item-description",
      text: "Create an OAuth client (type: Desktop app) in Google Cloud Console, enable the Google Drive API, then paste the Client ID and Secret below and click Connect. Desktop only."
    });
    new import_obsidian2.Setting(containerEl).setName("Client ID").addText(
      (text) => text.setValue(this.plugin.settings.gdriveClientId).onChange(async (v) => {
        this.plugin.settings.gdriveClientId = v.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Client Secret").addText((text) => {
      text.inputEl.type = "password";
      text.setValue(this.plugin.settings.gdriveClientSecret).onChange(async (v) => {
        this.plugin.settings.gdriveClientSecret = v.trim();
        await this.plugin.saveSettings();
      });
    });
    const connected = this.plugin.drive.isConnected();
    new import_obsidian2.Setting(containerEl).setName("Connection").setDesc(connected ? "Connected to Google Drive." : "Not connected.").addButton(
      (b) => b.setButtonText(connected ? "Reconnect" : "Connect").setCta().onClick(async () => {
        if (!isDesktop()) {
          new import_obsidian2.Notice("Google Drive sign-in is desktop-only.");
          return;
        }
        try {
          new import_obsidian2.Notice("Opening Google sign-in in your browser\u2026");
          await this.plugin.drive.connect();
          new import_obsidian2.Notice("Connected to Google Drive.");
          this.display();
        } catch (e) {
          console.error("[RecentView] Google Drive connect failed", e);
          new import_obsidian2.Notice(`Google Drive connect failed: ${e.message}`, 12e3);
        }
      })
    ).addExtraButton(
      (b) => b.setIcon("log-out").setTooltip("Disconnect").onClick(async () => {
        await this.plugin.drive.disconnect();
        this.display();
      })
    );
  }
};
