/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD - do not edit directly. */
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RecentViewPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE_PROJECT_LIST = "recent-view-project-list";
var VIEW_TYPE_PROJECT_CONTENT = "recent-view-project-content";
var DEFAULT_SETTINGS = {
  dataNotePath: "RecentView.md"
};
var DATA_NOTE_HEADER = "# Recent View data\n\nThis note is managed by the **Recent View** plugin and stores this vault's projects. Avoid editing the JSON block below by hand.";
function genId() {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 8);
}
function buildDataNote(data) {
  return `${DATA_NOTE_HEADER}

\`\`\`json
${JSON.stringify(
    data,
    null,
    2
  )}
\`\`\`
`;
}
function parseDataNote(content) {
  var _a, _b;
  const match = content.match(/```json\s*([\s\S]*?)```/);
  if (!match)
    return null;
  try {
    const parsed = JSON.parse(match[1]);
    return {
      projects: (_a = parsed.projects) != null ? _a : [],
      activeProjectId: (_b = parsed.activeProjectId) != null ? _b : null
    };
  } catch (e) {
    return null;
  }
}
function showMenu(menu, event, paneEl, btn) {
  btn == null ? void 0 : btn.addClass("is-active");
  const prevPointerEvents = paneEl.style.pointerEvents;
  paneEl.style.pointerEvents = "none";
  menu.onHide(() => {
    btn == null ? void 0 : btn.removeClass("is-active");
    paneEl.style.pointerEvents = prevPointerEvents;
  });
  menu.showAtMouseEvent(event);
}
var RecentViewPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.data = { projects: [], activeProjectId: null };
    this.settings = { ...DEFAULT_SETTINGS };
    this.isActivating = false;
    this.noteWriteTimer = null;
    // Live tab group (pane) per project, kept alive so switching just shows/hides
    // panes instead of closing and reopening notes.
    this.projectGroups = /* @__PURE__ */ new Map();
  }
  async onload() {
    await this.loadAll();
    this.addSettingTab(new RecentViewSettingTab(this.app, this));
    this.registerView(
      VIEW_TYPE_PROJECT_LIST,
      (leaf) => new ProjectListView(leaf, this)
    );
    this.registerView(
      VIEW_TYPE_PROJECT_CONTENT,
      (leaf) => new ProjectContentView(leaf, this)
    );
    this.addRibbonIcon(
      "folder-kanban",
      "Recent View: projects",
      () => this.activateListView()
    );
    this.addCommand({
      id: "open-projects-pane",
      name: "Open projects pane",
      callback: () => this.activateListView()
    });
    this.addCommand({
      id: "new-project",
      name: "Create new project",
      callback: () => new ProjectEditModal(this.app, this, null).open()
    });
    this.addCommand({
      id: "save-current-tabs",
      name: "Save current tabs to active project",
      callback: () => {
        const n = this.saveActiveProjectTabs(true);
        const p = this.getActiveProject();
        new import_obsidian.Notice(
          p ? `RecentView: saved ${n} tab(s) to "${p.name}"` : "RecentView: no active project"
        );
      }
    });
    this.registerEvent(
      this.app.workspace.on("layout-change", () => this.saveActiveProjectTabs())
    );
    this.app.workspace.onLayoutReady(() => {
      this.activateListView();
      const active = this.getActiveProject();
      if (active)
        void this.openProject(active);
      const onVaultChange = () => this.refreshContentView();
      this.registerEvent(this.app.vault.on("create", onVaultChange));
      this.registerEvent(this.app.vault.on("delete", onVaultChange));
      this.registerEvent(
        this.app.vault.on("rename", (file, oldPath) => {
          this.handlePathRename(oldPath, file.path);
          this.refreshContentView();
        })
      );
    });
  }
  onunload() {
    if (this.noteWriteTimer !== null) {
      window.clearTimeout(this.noteWriteTimer);
      this.noteWriteTimer = null;
      void this.writeDataNote();
    }
  }
  /**
   * Load settings (from the plugin's data.json) and project data (from the
   * note inside the vault). Falls back to migrating legacy project data that
   * older versions stored in data.json.
   */
  async loadAll() {
    var _a, _b, _c, _d;
    const stored = (_a = await this.loadData()) != null ? _a : {};
    this.settings = {
      dataNotePath: stored.dataNotePath || DEFAULT_SETTINGS.dataNotePath
    };
    const fromNote = await this.readDataNote();
    if (fromNote) {
      this.data = fromNote;
    } else if (stored.projects) {
      this.data = {
        projects: stored.projects,
        activeProjectId: (_b = stored.activeProjectId) != null ? _b : null
      };
      await this.writeDataNote();
    } else {
      this.data = { projects: [], activeProjectId: null };
    }
    for (const project of this.data.projects) {
      project.lastOpenNotes = ((_c = project.lastOpenNotes) != null ? _c : []).map((n) => typeof n === "string" ? { path: n } : n);
      project.pinned = (_d = project.pinned) != null ? _d : [];
    }
  }
  async readDataNote() {
    const path = this.settings.dataNotePath;
    const adapter = this.app.vault.adapter;
    if (!path || !await adapter.exists(path))
      return null;
    try {
      return parseDataNote(await adapter.read(path));
    } catch (e) {
      return null;
    }
  }
  async writeDataNote() {
    const path = this.settings.dataNotePath;
    if (!path)
      return;
    const adapter = this.app.vault.adapter;
    const slash = path.lastIndexOf("/");
    if (slash > 0) {
      const dir = path.slice(0, slash);
      if (!await adapter.exists(dir))
        await adapter.mkdir(dir);
    }
    await adapter.write(path, buildDataNote(this.data));
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Persist settings immediately and schedule a debounced write of the project
   * data note (avoids hammering the vault/sync on every layout change).
   */
  async persist() {
    await this.saveSettings();
    if (this.noteWriteTimer !== null)
      window.clearTimeout(this.noteWriteTimer);
    this.noteWriteTimer = window.setTimeout(() => {
      this.noteWriteTimer = null;
      void this.writeDataNote();
    }, 600);
  }
  /** Persist immediately, used for infrequent but important edits. */
  async persistNow() {
    if (this.noteWriteTimer !== null) {
      window.clearTimeout(this.noteWriteTimer);
      this.noteWriteTimer = null;
    }
    await this.saveSettings();
    await this.writeDataNote();
  }
  getActiveProject() {
    var _a;
    return (_a = this.data.projects.find((p) => p.id === this.data.activeProjectId)) != null ? _a : null;
  }
  async togglePin(project, path) {
    if (!project.pinned)
      project.pinned = [];
    const i = project.pinned.indexOf(path);
    if (i >= 0)
      project.pinned.splice(i, 1);
    else
      project.pinned.push(path);
    await this.persistNow();
    this.refreshContentView();
  }
  /** Update stored paths across all projects when a file/folder is renamed. */
  handlePathRename(oldPath, newPath) {
    var _a;
    const remap = (p) => {
      if (p === oldPath)
        return newPath;
      if (p.startsWith(oldPath + "/"))
        return newPath + p.slice(oldPath.length);
      return p;
    };
    let changed = false;
    const track = (before, after) => {
      if (before !== after)
        changed = true;
      return after;
    };
    for (const project of this.data.projects) {
      project.folders = project.folders.map((f) => track(f, remap(f)));
      project.notes = project.notes.map((n) => track(n, remap(n)));
      project.pinned = ((_a = project.pinned) != null ? _a : []).map((p) => track(p, remap(p)));
      project.lastOpenNotes = project.lastOpenNotes.map((n) => ({
        ...n,
        path: track(n.path, remap(n.path))
      }));
    }
    if (changed)
      void this.persist();
  }
  /** Reorder pinned notes: move fromPath next to toPath (after or before). */
  async movePin(project, fromPath, toPath, after) {
    var _a;
    const pinned = (_a = project.pinned) != null ? _a : project.pinned = [];
    const from = pinned.indexOf(fromPath);
    if (from < 0)
      return;
    pinned.splice(from, 1);
    const target = pinned.indexOf(toPath);
    if (target < 0)
      pinned.push(fromPath);
    else
      pinned.splice(after ? target + 1 : target, 0, fromPath);
    await this.persistNow();
    this.refreshContentView();
  }
  async activateListView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_PROJECT_LIST)[0];
    if (!leaf) {
      const left = workspace.getLeftLeaf(false);
      if (!left)
        return;
      leaf = left;
      await leaf.setViewState({ type: VIEW_TYPE_PROJECT_LIST, active: true });
    }
    workspace.revealLeaf(leaf);
  }
  async activateContentView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_PROJECT_CONTENT)[0];
    if (!leaf) {
      const right = workspace.getRightLeaf(false);
      if (!right)
        return;
      leaf = right;
      await leaf.setViewState({
        type: VIEW_TYPE_PROJECT_CONTENT,
        active: true
      });
    }
    workspace.revealLeaf(leaf);
    this.refreshContentView();
  }
  refreshListView() {
    for (const leaf of this.app.workspace.getLeavesOfType(
      VIEW_TYPE_PROJECT_LIST
    )) {
      if (leaf.view instanceof ProjectListView)
        leaf.view.render();
    }
  }
  refreshContentView() {
    for (const leaf of this.app.workspace.getLeavesOfType(
      VIEW_TYPE_PROJECT_CONTENT
    )) {
      if (leaf.view instanceof ProjectContentView)
        leaf.view.render();
    }
  }
  /**
   * Open a project: show its live pane (tab group), creating it from the saved
   * notes the first time. Other projects' panes are hidden, not closed, so
   * their tabs keep their full editor state.
   */
  async openProject(project) {
    this.saveActiveProjectTabs();
    this.isActivating = true;
    this.data.activeProjectId = project.id;
    this.refreshListView();
    void this.activateContentView();
    try {
      let group = this.getLiveGroup(project.id);
      if (!group)
        group = await this.createProjectGroup(project);
      if (group) {
        this.projectGroups.set(project.id, group);
        this.applyGroupVisibility(project.id);
        this.applyWallpaper(project, group);
        this.focusGroup(group);
      }
    } catch (e) {
      console.error("[RecentView] failed to open project pane", e);
    }
    await this.persist();
    window.setTimeout(() => {
      this.isActivating = false;
    }, 150);
  }
  /** Build a new tab group for a project from its saved notes. */
  async createProjectGroup(project) {
    var _a;
    const notes = this.resolveNotes(project);
    const { workspace } = this.app;
    let firstLeaf;
    if (!this.hasAnyLiveGroup()) {
      const existing = [];
      workspace.iterateRootLeaves((leaf) => {
        existing.push(leaf);
      });
      firstLeaf = (_a = existing[0]) != null ? _a : workspace.getLeaf(false);
      for (const leaf of existing)
        if (leaf !== firstLeaf)
          leaf.detach();
    } else {
      const mru = workspace.getMostRecentLeaf(workspace.rootSplit);
      if (mru)
        workspace.setActiveLeaf(mru, { focus: false });
      firstLeaf = workspace.getLeaf("split");
    }
    if (notes.length === 0) {
      await firstLeaf.setViewState({ type: "empty" });
      return firstLeaf.parent;
    }
    const opened = [firstLeaf];
    await firstLeaf.openFile(notes[0].file, { eState: notes[0].eState });
    for (let i = 1; i < notes.length; i++) {
      const leaf = workspace.getLeaf("tab");
      await leaf.openFile(notes[i].file, { eState: notes[i].eState });
      opened.push(leaf);
    }
    const activeIndex = notes.findIndex((n) => n.active);
    workspace.setActiveLeaf(opened[activeIndex >= 0 ? activeIndex : 0], {
      focus: true
    });
    return firstLeaf.parent;
  }
  resolveNotes(project) {
    return project.lastOpenNotes.map((n) => ({
      file: this.app.vault.getAbstractFileByPath(n.path),
      eState: n.eState,
      active: n.active === true
    })).filter(
      (n) => n.file instanceof import_obsidian.TFile
    );
  }
  /** The container element of a tab group, or null if it's gone. */
  groupContainer(group) {
    const el = group.containerEl;
    return el != null ? el : null;
  }
  /** Return the project's tab group if it still exists in the layout. */
  getLiveGroup(projectId) {
    if (!projectId)
      return null;
    const group = this.projectGroups.get(projectId);
    if (!group)
      return null;
    const el = this.groupContainer(group);
    if (!el || !el.isConnected) {
      this.projectGroups.delete(projectId);
      return null;
    }
    return group;
  }
  getActiveGroup() {
    return this.getLiveGroup(this.data.activeProjectId);
  }
  hasAnyLiveGroup() {
    for (const [id] of this.projectGroups) {
      if (this.getLiveGroup(id))
        return true;
    }
    return false;
  }
  leafInGroup(leaf, group) {
    var _a;
    let node = leaf;
    while (node) {
      if (node === group)
        return true;
      node = (_a = node.parent) != null ? _a : null;
    }
    return false;
  }
  /** Show the active project's pane, hide all others. */
  applyGroupVisibility(activeId) {
    for (const [projectId, group] of [...this.projectGroups]) {
      const el = this.groupContainer(group);
      if (!el || !el.isConnected) {
        this.projectGroups.delete(projectId);
        continue;
      }
      if (projectId === activeId) {
        el.style.display = "";
        el.style.flexGrow = "1";
        el.style.flexShrink = "1";
        el.style.flexBasis = "0";
        el.style.minWidth = "0";
        el.style.width = "";
      } else {
        el.style.display = "none";
      }
    }
  }
  /** Focus the most recently active leaf inside a group so its tab is shown
   *  (preserves which tab was active within that pane). */
  focusGroup(group) {
    const leaf = this.app.workspace.getMostRecentLeaf(group);
    if (leaf)
      this.app.workspace.setActiveLeaf(leaf, { focus: true });
  }
  /** Focus the active project's pane (used before opening a note into it). */
  focusActiveGroup() {
    const group = this.getActiveGroup();
    if (group)
      this.focusGroup(group);
  }
  /** Apply (or clear) a project's wallpaper image on its pane container. */
  applyWallpaper(project, group) {
    const el = this.groupContainer(group);
    if (!el)
      return;
    const path = project.wallpaper;
    const file = path ? this.app.vault.getAbstractFileByPath(path) : null;
    if (file instanceof import_obsidian.TFile) {
      const url = this.app.vault.getResourcePath(file);
      el.style.backgroundImage = `url("${url}")`;
      el.style.backgroundSize = "cover";
      el.style.backgroundPosition = "center";
      el.style.backgroundRepeat = "no-repeat";
      el.addClass("rv-has-wallpaper");
    } else {
      el.style.backgroundImage = "";
      el.removeClass("rv-has-wallpaper");
    }
  }
  /** Re-apply the active project's wallpaper (e.g. after editing it). */
  refreshWallpaper() {
    const project = this.getActiveProject();
    const group = project && this.getLiveGroup(project.id);
    if (project && group)
      this.applyWallpaper(project, group);
  }
  saveActiveProjectTabs(force = false) {
    var _a;
    if (this.isActivating && !force)
      return -1;
    const project = this.getActiveProject();
    if (!project)
      return -1;
    const group = this.getLiveGroup(project.id);
    if (!group)
      return -1;
    const activeLeaf = this.app.workspace.getMostRecentLeaf(
      this.app.workspace.rootSplit
    );
    const activePath = (_a = activeLeaf == null ? void 0 : activeLeaf.getViewState().state) == null ? void 0 : _a.file;
    const open = [];
    this.app.workspace.iterateRootLeaves((leaf) => {
      var _a2;
      if (!this.leafInGroup(leaf, group))
        return;
      const filePath = (_a2 = leaf.getViewState().state) == null ? void 0 : _a2.file;
      if (typeof filePath === "string" && !open.some((o) => o.path === filePath)) {
        open.push({
          path: filePath,
          eState: leaf.getEphemeralState(),
          active: filePath === activePath
        });
      }
    });
    project.lastOpenNotes = open;
    void this.persist();
    return open.length;
  }
  async deleteProject(project) {
    const group = this.projectGroups.get(project.id);
    if (group) {
      const toClose = [];
      this.app.workspace.iterateRootLeaves((leaf) => {
        if (this.leafInGroup(leaf, group))
          toClose.push(leaf);
      });
      for (const leaf of toClose)
        leaf.detach();
      this.projectGroups.delete(project.id);
    }
    this.data.projects = this.data.projects.filter((p) => p.id !== project.id);
    if (this.data.activeProjectId === project.id) {
      this.data.activeProjectId = null;
    }
    await this.persistNow();
    this.refreshListView();
    this.refreshContentView();
  }
};
var ProjectListView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_PROJECT_LIST;
  }
  getDisplayText() {
    return "Projects";
  }
  getIcon() {
    return "folder-kanban";
  }
  async onOpen() {
    this.render();
  }
  render() {
    const c = this.contentEl;
    c.empty();
    c.addClass("recent-view-list");
    const header = c.createDiv({ cls: "rv-header" });
    header.createEl("span", { cls: "rv-header-title", text: "Projects" });
    const addBtn = header.createEl("button", {
      cls: "rv-new-btn",
      text: "+ New"
    });
    addBtn.onclick = () => new ProjectEditModal(this.plugin.app, this.plugin, null).open();
    const list = c.createDiv({ cls: "rv-project-list" });
    if (this.plugin.data.projects.length === 0) {
      list.createDiv({
        cls: "rv-empty",
        text: 'No projects yet. Click "+ New" to create one.'
      });
      return;
    }
    for (const project of this.plugin.data.projects) {
      const box = list.createDiv({ cls: "rv-project-box" });
      if (project.id === this.plugin.data.activeProjectId) {
        box.addClass("is-active");
      }
      const info = box.createDiv({ cls: "rv-project-info" });
      info.createDiv({ cls: "rv-project-name", text: project.name });
      if (project.description) {
        info.createDiv({ cls: "rv-project-desc", text: project.description });
      }
      const actions = box.createDiv({ cls: "rv-project-actions" });
      const menuBtn = actions.createEl("button", { cls: "rv-icon-btn" });
      (0, import_obsidian.setIcon)(menuBtn, "more-vertical");
      menuBtn.setAttribute("aria-label", "Project options");
      menuBtn.onclick = (e) => {
        e.stopPropagation();
        const menu = new import_obsidian.Menu();
        menu.addItem(
          (item) => item.setTitle("Edit project").setIcon("pencil").onClick(
            () => new ProjectEditModal(this.plugin.app, this.plugin, project).open()
          )
        );
        menu.addItem(
          (item) => item.setTitle("Delete project").setIcon("trash-2").onClick(
            () => new ConfirmModal(
              this.plugin.app,
              `Delete project "${project.name}"?`,
              () => void this.plugin.deleteProject(project)
            ).open()
          )
        );
        showMenu(menu, e, this.contentEl, menuBtn);
      };
      box.onclick = () => void this.plugin.openProject(project);
    }
  }
};
var ProjectContentView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.reordering = false;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_PROJECT_CONTENT;
  }
  getDisplayText() {
    return "Project contents";
  }
  getIcon() {
    return "list-tree";
  }
  async onOpen() {
    this.render();
  }
  render() {
    var _a, _b;
    const c = this.contentEl;
    c.empty();
    c.addClass("recent-view-content");
    const header = c.createDiv({ cls: "rv-content-header" });
    const info = header.createDiv({ cls: "rv-content-headinfo" });
    const project = this.plugin.getActiveProject();
    info.createEl("h4", {
      cls: "rv-content-title",
      text: project ? project.name : "Project contents"
    });
    const menuBtn = header.createEl("button", {
      cls: "rv-icon-btn rv-content-menu"
    });
    (0, import_obsidian.setIcon)(menuBtn, "more-vertical");
    menuBtn.setAttribute("aria-label", "More options");
    menuBtn.onclick = (e) => {
      const menu = new import_obsidian.Menu();
      menu.addItem(
        (item) => item.setTitle("Refresh").setIcon("refresh-cw").onClick(() => this.render())
      );
      showMenu(menu, e, this.contentEl, menuBtn);
    };
    if (!project) {
      c.createDiv({
        cls: "rv-empty",
        text: "Open a project to see its folders and notes."
      });
      return;
    }
    if (project.description) {
      info.createDiv({ cls: "rv-project-desc", text: project.description });
    }
    const pinnedFiles = ((_a = project.pinned) != null ? _a : []).map((path) => this.plugin.app.vault.getAbstractFileByPath(path)).filter((f) => f instanceof import_obsidian.TFile);
    if (pinnedFiles.length > 0) {
      const section = c.createDiv({ cls: "rv-folder-section rv-pinned-section" });
      if (this.reordering)
        section.addClass("rv-reordering");
      const head = section.createDiv({ cls: "rv-folder-head" });
      (0, import_obsidian.setIcon)(head.createSpan({ cls: "rv-folder-icon" }), "pin");
      head.createSpan({ text: "Pinned" });
      const menuBtn2 = head.createEl("button", {
        cls: "rv-icon-btn rv-head-menu"
      });
      (0, import_obsidian.setIcon)(menuBtn2, "more-vertical");
      menuBtn2.setAttribute("aria-label", "More options");
      menuBtn2.onclick = (e) => {
        e.stopPropagation();
        const menu = new import_obsidian.Menu();
        menu.addItem(
          (i) => i.setTitle(this.reordering ? "Done reordering" : "Reorder").setIcon(this.reordering ? "check" : "arrow-up-down").onClick(() => {
            this.reordering = !this.reordering;
            this.render();
          })
        );
        showMenu(menu, e, this.contentEl, menuBtn2);
      };
      const fileList = section.createDiv({ cls: "rv-file-list" });
      for (const file of pinnedFiles) {
        const item = this.renderFileItem(fileList, file);
        if (this.reordering)
          this.makePinDraggable(item, file, project);
      }
    } else if (this.reordering) {
      this.reordering = false;
    }
    for (const folderPath of project.folders) {
      const folder = this.plugin.app.vault.getAbstractFileByPath(folderPath);
      const section = c.createDiv({ cls: "rv-folder-section" });
      const head = section.createDiv({ cls: "rv-folder-head" });
      (0, import_obsidian.setIcon)(head.createSpan({ cls: "rv-folder-icon" }), "folder");
      head.createSpan({ text: (_b = folder == null ? void 0 : folder.name) != null ? _b : folderPath });
      if (folder instanceof import_obsidian.TFolder) {
        const menuBtn2 = head.createEl("button", {
          cls: "rv-icon-btn rv-head-menu"
        });
        (0, import_obsidian.setIcon)(menuBtn2, "more-vertical");
        menuBtn2.setAttribute("aria-label", "More options");
        menuBtn2.onclick = (e) => {
          e.stopPropagation();
          const menu = new import_obsidian.Menu();
          menu.addItem(
            (i) => i.setTitle("Rename").setIcon("pencil").onClick(() => new RenameModal(this.plugin.app, folder).open())
          );
          showMenu(menu, e, this.contentEl, menuBtn2);
        };
      }
      const fileList = section.createDiv({ cls: "rv-file-list" });
      if (folder instanceof import_obsidian.TFolder) {
        const count = this.renderFolderTree(fileList, folder);
        if (count === 0) {
          fileList.createDiv({ cls: "rv-empty-sm", text: "No notes" });
        }
      } else {
        fileList.createDiv({ cls: "rv-empty-sm", text: "Folder not found" });
      }
    }
    if (project.notes.length > 0) {
      const section = c.createDiv({ cls: "rv-folder-section" });
      const head = section.createDiv({ cls: "rv-folder-head" });
      (0, import_obsidian.setIcon)(head.createSpan({ cls: "rv-folder-icon" }), "file-text");
      head.createSpan({ text: "Notes" });
      const fileList = section.createDiv({ cls: "rv-file-list" });
      const looseNotes = project.notes.map((path) => this.plugin.app.vault.getAbstractFileByPath(path)).filter((f) => f instanceof import_obsidian.TFile).sort((a, b) => a.basename.localeCompare(b.basename));
      for (const file of looseNotes)
        this.renderFileItem(fileList, file);
    }
  }
  renderFileItem(container, file) {
    const item = container.createDiv({ cls: "rv-file-item" });
    (0, import_obsidian.setIcon)(item.createSpan({ cls: "rv-file-icon" }), "file");
    item.createSpan({ cls: "rv-file-name", text: file.basename });
    item.onclick = () => this.openOrFocus(file);
    const menuBtn = item.createEl("button", { cls: "rv-icon-btn rv-item-menu" });
    (0, import_obsidian.setIcon)(menuBtn, "more-vertical");
    menuBtn.setAttribute("aria-label", "More options");
    menuBtn.onclick = (e) => {
      e.stopPropagation();
      this.showFileMenu(e, file, menuBtn);
    };
    return item;
  }
  /**
   * Render a folder's notes (sorted), then each subfolder's notes below a
   * separator labelled with the subfolder name (recursively). Returns the total
   * number of notes rendered.
   */
  renderFolderTree(container, folder) {
    const children = [...folder.children];
    const files = children.filter((c) => c instanceof import_obsidian.TFile && c.extension === "md").sort((a, b) => a.basename.localeCompare(b.basename));
    const subfolders = children.filter((c) => c instanceof import_obsidian.TFolder).sort((a, b) => a.name.localeCompare(b.name));
    let count = 0;
    for (const f of files) {
      this.renderFileItem(container, f);
      count++;
    }
    for (const sub of subfolders) {
      if (countMarkdown(sub) === 0)
        continue;
      const sep = container.createDiv({ cls: "rv-subfolder-sep" });
      sep.createSpan({ cls: "rv-subfolder-label", text: sub.name });
      count += this.renderFolderTree(container, sub);
    }
    return count;
  }
  showFileMenu(e, file, btn) {
    var _a;
    const project = this.plugin.getActiveProject();
    const menu = new import_obsidian.Menu();
    if (project) {
      const pinned = ((_a = project.pinned) != null ? _a : []).includes(file.path);
      menu.addItem(
        (i) => i.setTitle(pinned ? "Unpin from top" : "Pin to top").setIcon(pinned ? "pin-off" : "pin").onClick(() => void this.plugin.togglePin(project, file.path))
      );
    }
    menu.addItem(
      (i) => i.setTitle("Rename").setIcon("pencil").onClick(() => new RenameModal(this.plugin.app, file).open())
    );
    showMenu(menu, e, this.contentEl, btn);
  }
  /** Make a pinned item draggable so the pinned list can be reordered. */
  makePinDraggable(item, file, project) {
    item.draggable = true;
    item.addClass("rv-pin-draggable");
    item.addEventListener("dragstart", (e) => {
      var _a;
      (_a = e.dataTransfer) == null ? void 0 : _a.setData("text/plain", file.path);
      if (e.dataTransfer)
        e.dataTransfer.effectAllowed = "move";
      item.addClass("rv-dragging");
    });
    item.addEventListener("dragend", () => item.removeClass("rv-dragging"));
    item.addEventListener("dragover", (e) => {
      e.preventDefault();
      if (e.dataTransfer)
        e.dataTransfer.dropEffect = "move";
      const rect = item.getBoundingClientRect();
      const after = e.clientY > rect.top + rect.height / 2;
      item.toggleClass("rv-drop-after", after);
      item.toggleClass("rv-drop-before", !after);
    });
    item.addEventListener("dragleave", () => {
      item.removeClass("rv-drop-before");
      item.removeClass("rv-drop-after");
    });
    item.addEventListener("drop", (e) => {
      var _a;
      e.preventDefault();
      const after = item.hasClass("rv-drop-after");
      item.removeClass("rv-drop-before");
      item.removeClass("rv-drop-after");
      const fromPath = (_a = e.dataTransfer) == null ? void 0 : _a.getData("text/plain");
      if (fromPath && fromPath !== file.path) {
        void this.plugin.movePin(project, fromPath, file.path, after);
      }
    });
  }
  openOrFocus(file) {
    const { workspace } = this.plugin.app;
    const group = this.plugin.getActiveGroup();
    const existing = this.findLeafForFile(file, group);
    if (existing) {
      workspace.setActiveLeaf(existing, { focus: true });
      workspace.revealLeaf(existing);
      return;
    }
    if (group)
      this.plugin.focusActiveGroup();
    void workspace.getLeaf("tab").openFile(file);
  }
  findLeafForFile(file, group) {
    let found = null;
    this.plugin.app.workspace.iterateRootLeaves((leaf) => {
      var _a;
      if (found)
        return;
      if (group && !this.plugin.leafInGroup(leaf, group))
        return;
      if (((_a = leaf.getViewState().state) == null ? void 0 : _a.file) === file.path)
        found = leaf;
    });
    return found;
  }
};
var RenameModal = class extends import_obsidian.Modal {
  constructor(app, item) {
    super(app);
    this.item = item;
    this.isFile = item instanceof import_obsidian.TFile;
    this.value = item instanceof import_obsidian.TFile ? item.basename : item.name;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("recent-view-modal");
    contentEl.createEl("h3", {
      text: this.isFile ? "Rename note" : "Rename folder"
    });
    let inputEl = null;
    new import_obsidian.Setting(contentEl).setName("New name").addText((t) => {
      t.setValue(this.value).onChange((v) => this.value = v);
      inputEl = t.inputEl;
      t.inputEl.addEventListener("keydown", (e) => {
        if (e.key === "Enter") {
          e.preventDefault();
          void this.doRename();
        }
      });
    });
    const footer = contentEl.createDiv({ cls: "rv-modal-footer" });
    const ok = footer.createEl("button", { cls: "mod-cta", text: "Rename" });
    ok.onclick = () => void this.doRename();
    const cancel = footer.createEl("button", { text: "Cancel" });
    cancel.onclick = () => this.close();
    window.setTimeout(() => {
      inputEl == null ? void 0 : inputEl.focus();
      inputEl == null ? void 0 : inputEl.select();
    }, 0);
  }
  async doRename() {
    var _a;
    const name = this.value.trim();
    if (!name) {
      new import_obsidian.Notice("Name is required");
      return;
    }
    const parent = (_a = this.item.parent) == null ? void 0 : _a.path;
    const dir = parent && parent !== "/" ? `${parent}/` : "";
    const ext = this.item instanceof import_obsidian.TFile ? `.${this.item.extension}` : "";
    const newPath = `${dir}${name}${ext}`;
    if (newPath === this.item.path) {
      this.close();
      return;
    }
    try {
      await this.app.fileManager.renameFile(this.item, newPath);
    } catch (e) {
      new import_obsidian.Notice(`Rename failed: ${e.message}`);
      return;
    }
    this.close();
  }
};
function countMarkdown(folder) {
  let n = 0;
  for (const child of folder.children) {
    if (child instanceof import_obsidian.TFolder)
      n += countMarkdown(child);
    else if (child instanceof import_obsidian.TFile && child.extension === "md")
      n++;
  }
  return n;
}
var ProjectEditModal = class extends import_obsidian.Modal {
  constructor(app, plugin, project) {
    var _a, _b, _c, _d, _e;
    super(app);
    this.plugin = plugin;
    this.project = project;
    this.name = (_a = project == null ? void 0 : project.name) != null ? _a : "";
    this.description = (_b = project == null ? void 0 : project.description) != null ? _b : "";
    this.folders = [...(_c = project == null ? void 0 : project.folders) != null ? _c : []];
    this.notes = [...(_d = project == null ? void 0 : project.notes) != null ? _d : []];
    this.wallpaper = (_e = project == null ? void 0 : project.wallpaper) != null ? _e : "";
  }
  onOpen() {
    this.renderForm();
  }
  renderForm() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("recent-view-modal");
    contentEl.createEl("h3", {
      text: this.project ? "Edit project" : "New project"
    });
    new import_obsidian.Setting(contentEl).setName("Name").addText(
      (t) => t.setPlaceholder("Project name").setValue(this.name).onChange((v) => this.name = v)
    );
    new import_obsidian.Setting(contentEl).setName("Description").addTextArea(
      (t) => t.setPlaceholder("What is this project about?").setValue(this.description).onChange((v) => this.description = v)
    );
    new import_obsidian.Setting(contentEl).setName("Folders").setDesc("Folders included in this project").addButton(
      (b) => b.setButtonText("Add folder").onClick(() => {
        new FolderSuggestModal(this.app, (folder) => {
          if (!this.folders.includes(folder.path)) {
            this.folders.push(folder.path);
          }
          this.renderForm();
        }).open();
      })
    );
    this.renderChipList(contentEl, this.folders, (path) => {
      this.folders = this.folders.filter((x) => x !== path);
      this.renderForm();
    });
    new import_obsidian.Setting(contentEl).setName("Notes").setDesc("Specific notes included in this project").addButton(
      (b) => b.setButtonText("Add note").onClick(() => {
        new FileSuggestModal(this.app, (file) => {
          if (!this.notes.includes(file.path))
            this.notes.push(file.path);
          this.renderForm();
        }).open();
      })
    );
    this.renderChipList(contentEl, this.notes, (path) => {
      this.notes = this.notes.filter((x) => x !== path);
      this.renderForm();
    });
    const wp = new import_obsidian.Setting(contentEl).setName("Wallpaper").setDesc("Image shown behind this project's empty pane").addButton(
      (b) => b.setButtonText("Choose image").onClick(() => {
        new ImageSuggestModal(this.app, (file) => {
          this.wallpaper = file.path;
          this.renderForm();
        }).open();
      })
    );
    if (this.wallpaper) {
      wp.addButton(
        (b) => b.setButtonText("Clear").onClick(() => {
          this.wallpaper = "";
          this.renderForm();
        })
      );
    }
    if (this.wallpaper) {
      const row = contentEl.createDiv({ cls: "rv-modal-list" });
      row.createDiv({ cls: "rv-modal-row" }).createSpan({ cls: "rv-modal-row-path", text: this.wallpaper });
    }
    const footer = contentEl.createDiv({ cls: "rv-modal-footer" });
    const saveBtn = footer.createEl("button", {
      cls: "mod-cta",
      text: "Save"
    });
    saveBtn.onclick = () => void this.save();
    const cancelBtn = footer.createEl("button", { text: "Cancel" });
    cancelBtn.onclick = () => this.close();
  }
  renderChipList(parent, items, onRemove) {
    if (items.length === 0)
      return;
    const list = parent.createDiv({ cls: "rv-modal-list" });
    for (const path of items) {
      const row = list.createDiv({ cls: "rv-modal-row" });
      row.createSpan({ cls: "rv-modal-row-path", text: path });
      const rm = row.createEl("button", { cls: "rv-icon-btn" });
      (0, import_obsidian.setIcon)(rm, "x");
      rm.onclick = () => onRemove(path);
    }
  }
  async save() {
    if (!this.name.trim()) {
      new import_obsidian.Notice("Project name is required");
      return;
    }
    if (this.project) {
      this.project.name = this.name.trim();
      this.project.description = this.description;
      this.project.folders = this.folders;
      this.project.notes = this.notes;
      this.project.wallpaper = this.wallpaper || void 0;
    } else {
      this.plugin.data.projects.push({
        id: genId(),
        name: this.name.trim(),
        description: this.description,
        folders: this.folders,
        notes: this.notes,
        lastOpenNotes: [],
        pinned: [],
        wallpaper: this.wallpaper || void 0
      });
    }
    await this.plugin.persistNow();
    this.plugin.refreshListView();
    this.plugin.refreshContentView();
    this.plugin.refreshWallpaper();
    this.close();
  }
};
var FolderSuggestModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, onChoose) {
    super(app);
    this.onChoose = onChoose;
    this.setPlaceholder("Pick a folder");
  }
  getItems() {
    const folders = [];
    import_obsidian.Vault.recurseChildren(this.app.vault.getRoot(), (f) => {
      if (f instanceof import_obsidian.TFolder)
        folders.push(f);
    });
    return folders;
  }
  getItemText(item) {
    return item.path === "/" ? "/ (vault root)" : item.path;
  }
  onChooseItem(item) {
    this.onChoose(item);
  }
};
var FileSuggestModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, onChoose) {
    super(app);
    this.onChoose = onChoose;
    this.setPlaceholder("Pick a note");
  }
  getItems() {
    return this.app.vault.getMarkdownFiles();
  }
  getItemText(item) {
    return item.path;
  }
  onChooseItem(item) {
    this.onChoose(item);
  }
};
var IMAGE_EXTENSIONS = ["png", "jpg", "jpeg", "gif", "webp", "svg", "bmp", "avif"];
var ImageSuggestModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, onChoose) {
    super(app);
    this.onChoose = onChoose;
    this.setPlaceholder("Pick an image");
  }
  getItems() {
    return this.app.vault.getFiles().filter((f) => IMAGE_EXTENSIONS.includes(f.extension.toLowerCase()));
  }
  getItemText(item) {
    return item.path;
  }
  onChooseItem(item) {
    this.onChoose(item);
  }
};
var ConfirmModal = class extends import_obsidian.Modal {
  constructor(app, message, onConfirm) {
    super(app);
    this.message = message;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("p", { text: this.message });
    const footer = contentEl.createDiv({ cls: "rv-modal-footer" });
    const yes = footer.createEl("button", { cls: "mod-warning", text: "Delete" });
    yes.onclick = () => {
      this.onConfirm();
      this.close();
    };
    const no = footer.createEl("button", { text: "Cancel" });
    no.onclick = () => this.close();
  }
};
var RecentViewSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Data note path").setDesc(
      "Vault-relative path of the note that stores this vault's projects. Stored inside the vault so the data is per-vault and travels with it."
    ).addText(
      (text) => text.setPlaceholder(DEFAULT_SETTINGS.dataNotePath).setValue(this.plugin.settings.dataNotePath).onChange(async (value) => {
        const next = value.trim() || DEFAULT_SETTINGS.dataNotePath;
        if (next === this.plugin.settings.dataNotePath)
          return;
        this.plugin.settings.dataNotePath = next;
        await this.plugin.persistNow();
      })
    );
  }
};
