/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD - do not edit directly. */
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RecentViewPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE_PROJECT_LIST = "recent-view-project-list";
var VIEW_TYPE_PROJECT_CONTENT = "recent-view-project-content";
var DEFAULT_DATA = {
  projects: [],
  activeProjectId: null
};
function genId() {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 8);
}
var RecentViewPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.data = DEFAULT_DATA;
    this.isActivating = false;
  }
  async onload() {
    this.data = Object.assign({}, DEFAULT_DATA, await this.loadData());
    this.registerView(
      VIEW_TYPE_PROJECT_LIST,
      (leaf) => new ProjectListView(leaf, this)
    );
    this.registerView(
      VIEW_TYPE_PROJECT_CONTENT,
      (leaf) => new ProjectContentView(leaf, this)
    );
    this.addRibbonIcon(
      "folder-kanban",
      "Recent View: projects",
      () => this.activateListView()
    );
    this.addCommand({
      id: "open-projects-pane",
      name: "Open projects pane",
      callback: () => this.activateListView()
    });
    this.addCommand({
      id: "new-project",
      name: "Create new project",
      callback: () => new ProjectEditModal(this.app, this, null).open()
    });
    this.addCommand({
      id: "save-current-tabs",
      name: "Save current tabs to active project",
      callback: () => {
        const n = this.saveActiveProjectTabs(true);
        const p = this.getActiveProject();
        new import_obsidian.Notice(
          p ? `RecentView: saved ${n} tab(s) to "${p.name}"` : "RecentView: no active project"
        );
      }
    });
    this.registerEvent(
      this.app.workspace.on("layout-change", () => this.saveActiveProjectTabs())
    );
    this.app.workspace.onLayoutReady(() => this.activateListView());
  }
  async persist() {
    await this.saveData(this.data);
  }
  getActiveProject() {
    var _a;
    return (_a = this.data.projects.find((p) => p.id === this.data.activeProjectId)) != null ? _a : null;
  }
  async activateListView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_PROJECT_LIST)[0];
    if (!leaf) {
      const left = workspace.getLeftLeaf(false);
      if (!left)
        return;
      leaf = left;
      await leaf.setViewState({ type: VIEW_TYPE_PROJECT_LIST, active: true });
    }
    workspace.revealLeaf(leaf);
  }
  async activateContentView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_PROJECT_CONTENT)[0];
    if (!leaf) {
      const right = workspace.getRightLeaf(false);
      if (!right)
        return;
      leaf = right;
      await leaf.setViewState({
        type: VIEW_TYPE_PROJECT_CONTENT,
        active: true
      });
    }
    workspace.revealLeaf(leaf);
    this.refreshContentView();
  }
  refreshListView() {
    for (const leaf of this.app.workspace.getLeavesOfType(
      VIEW_TYPE_PROJECT_LIST
    )) {
      if (leaf.view instanceof ProjectListView)
        leaf.view.render();
    }
  }
  refreshContentView() {
    for (const leaf of this.app.workspace.getLeavesOfType(
      VIEW_TYPE_PROJECT_CONTENT
    )) {
      if (leaf.view instanceof ProjectContentView)
        leaf.view.render();
    }
  }
  /**
   * Opening a project: close every open tab in the main area, then restore the
   * notes that were open the last time this project was active.
   */
  async openProject(project) {
    var _a;
    this.saveActiveProjectTabs();
    this.isActivating = true;
    this.data.activeProjectId = project.id;
    this.refreshListView();
    void this.activateContentView();
    const existing = [];
    this.app.workspace.iterateRootLeaves((leaf) => {
      existing.push(leaf);
    });
    const files = project.lastOpenNotes.map((p) => this.app.vault.getAbstractFileByPath(p)).filter((f) => f instanceof import_obsidian.TFile);
    if (files.length === 0) {
      for (const leaf of existing)
        leaf.detach();
    } else {
      const target = (_a = existing[0]) != null ? _a : this.app.workspace.getLeaf(false);
      for (const leaf of existing) {
        if (leaf !== target)
          leaf.detach();
      }
      await target.openFile(files[0]);
      for (let i = 1; i < files.length; i++) {
        await this.app.workspace.getLeaf("tab").openFile(files[i]);
      }
      this.app.workspace.setActiveLeaf(target, { focus: false });
    }
    await this.persist();
    window.setTimeout(() => {
      this.isActivating = false;
    }, 150);
  }
  saveActiveProjectTabs(force = false) {
    if (this.isActivating && !force)
      return -1;
    const project = this.getActiveProject();
    if (!project)
      return -1;
    const open = [];
    this.app.workspace.iterateRootLeaves((leaf) => {
      var _a;
      const filePath = (_a = leaf.getViewState().state) == null ? void 0 : _a.file;
      if (typeof filePath === "string" && !open.includes(filePath)) {
        open.push(filePath);
      }
    });
    project.lastOpenNotes = open;
    void this.persist();
    return open.length;
  }
  async deleteProject(project) {
    this.data.projects = this.data.projects.filter((p) => p.id !== project.id);
    if (this.data.activeProjectId === project.id) {
      this.data.activeProjectId = null;
    }
    await this.persist();
    this.refreshListView();
    this.refreshContentView();
  }
};
var ProjectListView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_PROJECT_LIST;
  }
  getDisplayText() {
    return "Projects";
  }
  getIcon() {
    return "folder-kanban";
  }
  async onOpen() {
    this.render();
  }
  render() {
    const c = this.contentEl;
    c.empty();
    c.addClass("recent-view-list");
    const header = c.createDiv({ cls: "rv-header" });
    header.createEl("span", { cls: "rv-header-title", text: "Projects" });
    const addBtn = header.createEl("button", {
      cls: "rv-new-btn",
      text: "+ New"
    });
    addBtn.onclick = () => new ProjectEditModal(this.plugin.app, this.plugin, null).open();
    const list = c.createDiv({ cls: "rv-project-list" });
    if (this.plugin.data.projects.length === 0) {
      list.createDiv({
        cls: "rv-empty",
        text: 'No projects yet. Click "+ New" to create one.'
      });
      return;
    }
    for (const project of this.plugin.data.projects) {
      const box = list.createDiv({ cls: "rv-project-box" });
      if (project.id === this.plugin.data.activeProjectId) {
        box.addClass("is-active");
      }
      const info = box.createDiv({ cls: "rv-project-info" });
      info.createDiv({ cls: "rv-project-name", text: project.name });
      if (project.description) {
        info.createDiv({ cls: "rv-project-desc", text: project.description });
      }
      const actions = box.createDiv({ cls: "rv-project-actions" });
      const editBtn = actions.createEl("button", { cls: "rv-icon-btn" });
      (0, import_obsidian.setIcon)(editBtn, "pencil");
      editBtn.setAttribute("aria-label", "Edit project");
      editBtn.onclick = (e) => {
        e.stopPropagation();
        new ProjectEditModal(this.plugin.app, this.plugin, project).open();
      };
      const delBtn = actions.createEl("button", { cls: "rv-icon-btn" });
      (0, import_obsidian.setIcon)(delBtn, "trash-2");
      delBtn.setAttribute("aria-label", "Delete project");
      delBtn.onclick = (e) => {
        e.stopPropagation();
        new ConfirmModal(
          this.plugin.app,
          `Delete project "${project.name}"?`,
          () => void this.plugin.deleteProject(project)
        ).open();
      };
      box.onclick = () => void this.plugin.openProject(project);
    }
  }
};
var ProjectContentView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_PROJECT_CONTENT;
  }
  getDisplayText() {
    return "Project contents";
  }
  getIcon() {
    return "list-tree";
  }
  async onOpen() {
    this.render();
  }
  render() {
    var _a;
    const c = this.contentEl;
    c.empty();
    c.addClass("recent-view-content");
    const project = this.plugin.getActiveProject();
    if (!project) {
      c.createDiv({
        cls: "rv-empty",
        text: "Open a project to see its folders and notes."
      });
      return;
    }
    c.createEl("h4", { cls: "rv-content-title", text: project.name });
    if (project.description) {
      c.createDiv({ cls: "rv-project-desc", text: project.description });
    }
    for (const folderPath of project.folders) {
      const folder = this.plugin.app.vault.getAbstractFileByPath(folderPath);
      const section = c.createDiv({ cls: "rv-folder-section" });
      const head = section.createDiv({ cls: "rv-folder-head" });
      (0, import_obsidian.setIcon)(head.createSpan({ cls: "rv-folder-icon" }), "folder");
      head.createSpan({ text: (_a = folder == null ? void 0 : folder.name) != null ? _a : folderPath });
      const fileList = section.createDiv({ cls: "rv-file-list" });
      if (folder instanceof import_obsidian.TFolder) {
        const files = collectMarkdown(folder);
        if (files.length === 0) {
          fileList.createDiv({ cls: "rv-empty-sm", text: "No notes" });
        }
        for (const f of files)
          this.renderFileItem(fileList, f);
      } else {
        fileList.createDiv({ cls: "rv-empty-sm", text: "Folder not found" });
      }
    }
    if (project.notes.length > 0) {
      const section = c.createDiv({ cls: "rv-folder-section" });
      const head = section.createDiv({ cls: "rv-folder-head" });
      (0, import_obsidian.setIcon)(head.createSpan({ cls: "rv-folder-icon" }), "file-text");
      head.createSpan({ text: "Notes" });
      const fileList = section.createDiv({ cls: "rv-file-list" });
      for (const path of project.notes) {
        const file = this.plugin.app.vault.getAbstractFileByPath(path);
        if (file instanceof import_obsidian.TFile)
          this.renderFileItem(fileList, file);
      }
    }
  }
  renderFileItem(container, file) {
    const item = container.createDiv({ cls: "rv-file-item" });
    (0, import_obsidian.setIcon)(item.createSpan({ cls: "rv-file-icon" }), "file");
    item.createSpan({ cls: "rv-file-name", text: file.basename });
    item.onclick = () => {
      void this.plugin.app.workspace.getLeaf("tab").openFile(file);
    };
  }
};
function collectMarkdown(folder) {
  const out = [];
  const walk = (f) => {
    for (const child of f.children) {
      if (child instanceof import_obsidian.TFolder)
        walk(child);
      else if (child instanceof import_obsidian.TFile && child.extension === "md")
        out.push(child);
    }
  };
  walk(folder);
  return out;
}
var ProjectEditModal = class extends import_obsidian.Modal {
  constructor(app, plugin, project) {
    var _a, _b, _c, _d;
    super(app);
    this.plugin = plugin;
    this.project = project;
    this.name = (_a = project == null ? void 0 : project.name) != null ? _a : "";
    this.description = (_b = project == null ? void 0 : project.description) != null ? _b : "";
    this.folders = [...(_c = project == null ? void 0 : project.folders) != null ? _c : []];
    this.notes = [...(_d = project == null ? void 0 : project.notes) != null ? _d : []];
  }
  onOpen() {
    this.renderForm();
  }
  renderForm() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("recent-view-modal");
    contentEl.createEl("h3", {
      text: this.project ? "Edit project" : "New project"
    });
    new import_obsidian.Setting(contentEl).setName("Name").addText(
      (t) => t.setPlaceholder("Project name").setValue(this.name).onChange((v) => this.name = v)
    );
    new import_obsidian.Setting(contentEl).setName("Description").addTextArea(
      (t) => t.setPlaceholder("What is this project about?").setValue(this.description).onChange((v) => this.description = v)
    );
    new import_obsidian.Setting(contentEl).setName("Folders").setDesc("Folders included in this project").addButton(
      (b) => b.setButtonText("Add folder").onClick(() => {
        new FolderSuggestModal(this.app, (folder) => {
          if (!this.folders.includes(folder.path)) {
            this.folders.push(folder.path);
          }
          this.renderForm();
        }).open();
      })
    );
    this.renderChipList(contentEl, this.folders, (path) => {
      this.folders = this.folders.filter((x) => x !== path);
      this.renderForm();
    });
    new import_obsidian.Setting(contentEl).setName("Notes").setDesc("Specific notes included in this project").addButton(
      (b) => b.setButtonText("Add note").onClick(() => {
        new FileSuggestModal(this.app, (file) => {
          if (!this.notes.includes(file.path))
            this.notes.push(file.path);
          this.renderForm();
        }).open();
      })
    );
    this.renderChipList(contentEl, this.notes, (path) => {
      this.notes = this.notes.filter((x) => x !== path);
      this.renderForm();
    });
    const footer = contentEl.createDiv({ cls: "rv-modal-footer" });
    const saveBtn = footer.createEl("button", {
      cls: "mod-cta",
      text: "Save"
    });
    saveBtn.onclick = () => void this.save();
    const cancelBtn = footer.createEl("button", { text: "Cancel" });
    cancelBtn.onclick = () => this.close();
  }
  renderChipList(parent, items, onRemove) {
    if (items.length === 0)
      return;
    const list = parent.createDiv({ cls: "rv-modal-list" });
    for (const path of items) {
      const row = list.createDiv({ cls: "rv-modal-row" });
      row.createSpan({ cls: "rv-modal-row-path", text: path });
      const rm = row.createEl("button", { cls: "rv-icon-btn" });
      (0, import_obsidian.setIcon)(rm, "x");
      rm.onclick = () => onRemove(path);
    }
  }
  async save() {
    if (!this.name.trim()) {
      new import_obsidian.Notice("Project name is required");
      return;
    }
    if (this.project) {
      this.project.name = this.name.trim();
      this.project.description = this.description;
      this.project.folders = this.folders;
      this.project.notes = this.notes;
    } else {
      this.plugin.data.projects.push({
        id: genId(),
        name: this.name.trim(),
        description: this.description,
        folders: this.folders,
        notes: this.notes,
        lastOpenNotes: []
      });
    }
    await this.plugin.persist();
    this.plugin.refreshListView();
    this.plugin.refreshContentView();
    this.close();
  }
};
var FolderSuggestModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, onChoose) {
    super(app);
    this.onChoose = onChoose;
    this.setPlaceholder("Pick a folder");
  }
  getItems() {
    const folders = [];
    import_obsidian.Vault.recurseChildren(this.app.vault.getRoot(), (f) => {
      if (f instanceof import_obsidian.TFolder)
        folders.push(f);
    });
    return folders;
  }
  getItemText(item) {
    return item.path === "/" ? "/ (vault root)" : item.path;
  }
  onChooseItem(item) {
    this.onChoose(item);
  }
};
var FileSuggestModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, onChoose) {
    super(app);
    this.onChoose = onChoose;
    this.setPlaceholder("Pick a note");
  }
  getItems() {
    return this.app.vault.getMarkdownFiles();
  }
  getItemText(item) {
    return item.path;
  }
  onChooseItem(item) {
    this.onChoose(item);
  }
};
var ConfirmModal = class extends import_obsidian.Modal {
  constructor(app, message, onConfirm) {
    super(app);
    this.message = message;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("p", { text: this.message });
    const footer = contentEl.createDiv({ cls: "rv-modal-footer" });
    const yes = footer.createEl("button", { cls: "mod-warning", text: "Delete" });
    yes.onclick = () => {
      this.onConfirm();
      this.close();
    };
    const no = footer.createEl("button", { text: "Cancel" });
    no.onclick = () => this.close();
  }
};
